### ISSUE TITLE
Melodic release 2.8.5???

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros-simulation/gazebo_ros_pkgs#1025]
According to https://github.com/ros-gbp/gazebo_ros_pkgs-release `gazebo_ros`@2.8.5 should be released. Though I can't install it by `apt-get`. Also on the ROS discourse page no sign of the 2.8.5 release. 

Could you please check the status?

**Comment by chapulina** [comment]
I can't see a [rosdistro PR](https://github.com/ros/rosdistro/pulls?q=is%3Apr+gazebo_ros_pkgs+%22melodic%2Fdistribution.yaml%22+is%3Aclosed+sort%3Aupdated-desc) either. I can cut a new release just in case.

**Comment by MatthijsBurgh** [comment]
That would be very helpful. Thanks!

**Comment by chapulina** [comment]
Bloomed: https://github.com/ros/rosdistro/pull/23373 :v:

**Comment by MatthijsBurgh** [comment]
Thanks!
