### ISSUE TITLE
How to check real flight with simulated flight. 

### ISSUE THREAD

**Issue by Sneha-hub115** [ros-simulation/gazebo_ros_pkgs#1055]
Hi,
I’m using ubuntu 18.04 to build the px4 code for gazebo and jmavsim using QGround control. I’m stuck with the following issues:

   1. How to check real flight with simulated flight using QGround control, gazebo, jmavsim.

Thank you

**Comment by chapulina** [comment]
Spam, see #1054, #1056, #1059
