### ISSUE TITLE
How to get logs in gazebo and jmavsim simulators

### ISSUE THREAD

**Issue by Sneha-hub115** [ros-simulation/gazebo_ros_pkgs#1056]
Hi,
I’m using ubuntu18.04 to build the px4 code for gazebo and jmavsim. I’m stuck with the following issues:
1. How to get log files in gazebo simulator.
2. Where i will get logs in gazebo simulator.
3. How to get log files in jmavsim simulator.
4. Where i will get logs in jmavsim simulator.

Thank you.

**Comment by chapulina** [comment]
@Sneha-hub115 , *again*, please don't ask questions here. Go to http://answers.gazebosim.org.

Similar issues: https://github.com/PX4/Firmware/issues/14291, https://github.com/ros-simulation/gazebo_ros_pkgs/issues/1054
