### ISSUE TITLE
How to replay the flight from logs in gazebo and jMAVSim

### ISSUE THREAD

**Issue by Sneha-hub115** [ros-simulation/gazebo_ros_pkgs#1059]
Hi,
I'm using ubuntu18.04 to build the px4 code for gazebo and jmavsim. I'm stuck with the following issue:

    1. How to replay the flight from logs in gazebo and jMAVSim simulators.

Thank you

**Comment by chapulina** [comment]
The user keeps posting px4 questions here even after pointing them to Gazebo Answers on #1056 and #1054. Looking at their account, they're posting the same on several other repositories too. It looks like a bot. I've blocked them from this organization.
