### ISSUE TITLE
gazebo_ros_control: Add URDF limit enforcement to default_robot_hw_sim.cpp

### ISSUE THREAD

**Issue by jim-rothrock** [ros-simulation/gazebo_ros_pkgs#111]
Using a JointVelocityController with an apparently small derivative gain, such as 0.01, results in large effort values being sent to Gazebo. If Gazebo 1.9.1 receives such a large effort value, it moves many of the model's links to the world origin, making the model unusable. Ultimately, this appears to be a Gazebo bug. In any case, though, controllers should obey the position, velocity, and effort limits specified in the URDF file. I have found that if the effort is clamped to the limit specified in the URDF, the "links moved to the origin" problem is avoided.

I made changes to the effort-based joint position and velocity controllers in ros_controllers, enforcing the velocity and effort limits specified in the URDF. However, Adolfo Rodriguez Tsouroukdissian pointed out that a better solution is to add a joint limits interface to default_robot_hw_sim.cpp. My questions are:

1) Is anyone already implementing this feature?
2) If not, does anyone have any objections to me adding it?

**Comment by davetcoleman** [comment]
@jbohren and I made gazebo_ros_control - I have no objections to adding it and and fairly certain no one has implemented it already.

**Comment by jim-rothrock** [comment]
On 09/12/2013 11:30 AM, Dave Coleman wrote:

> @jbohren https://github.com/jbohren and I made gazebo_ros_control - 
> I have no objects to adding it and and fairly certain no one has 
> implemented it already.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ros-simulation/gazebo_ros_pkgs/issues/111#issuecomment-24344513.

Okay. I'm now implementing it.

## 

Jim Rothrock | rothrockj@acm.org

**Comment by davetcoleman** [comment]
Thank you for implementing this - I assume this issue can be closed now?

**Comment by jim-rothrock** [comment]
Yes. Thanks for closing it.
