### ISSUE TITLE
gazebo_ros_control: plugin doesn't look for the robot model in its own namespace

### ISSUE THREAD

**Issue by micpalmia** [ros-simulation/gazebo_ros_pkgs#112]
When starting a Gazebo simulation that includes the plugin, it says

```
[ INFO] Starting gazebo_ros_control plugin in namespace: /youbot0/
[ INFO]: gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
```

One would expect for it to look for `/youbot0/robot_description`. 
Unless the `/robot_description param` is there, instead, it doesn't proceed.

If this is a known and required behaviour, or if the problem seems to be on my side, sorry in advance.

**Comment by davetcoleman** [comment]
In the URDF xml for the ros_control plugin, you can [specify the robot_description you desire the plugin to use](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/gazebo_ros_control_plugin.cpp#L94) by using the [robotParam](http://gazebosim.org/wiki/Tutorials/1.9/ROS_Control_with_Gazebo#Add_the_gazebo_ros_control_plugin) element. 

Whether or not it should by default look in the namespace, that is a good question that we might want to fix. I might recall though that by default you robots should just always load to /robot_description. Thoughts @jbohren ?

**Comment by micpalmia** [comment]
Maybe explaining the reason for my question would shed some more light on the issue.

When simulating one single robot, there's no big deal since the `robotParam` or the `robotNamespace` elements can be used to select the right namespace for robot_description (or whatever path is selected).

When simulating multiple robots, on the other side, or even when one wants to simulate a single robot in a very general way, a very cool thing to do (in my opinion) is to leave all the declarations in the description and controller in the main namespace and then, inside the launch file, group the nodes and parameters declarations inside different `<group ns="someNameSpace">` tags.

```
<group ns="/youbot0">
  <arg name="model" default="$(find youbot_description)/robots/youbot.urdf.xacro"/>
  <param name="robot_description" command="$(find xacro)/xacro.py '$(arg model)'" />

  <node name="spawn_robot" pkg="gazebo_ros" type="spawn_model"
        args="-param robot_description -urdf -model $(arg name)" /> 
</group>

<group ns="/youbot1"> ... </group>
```

(at the moment this doesn't work and I have to declare manually a general `robot_description` outside of the grouping)

If different robots have to be simulated in the same environment, things would get even more complicated. Having the default value for the robot model set to `/nameSpace/robot_description` would make a lot of sense to me, without any real drawback: if the controller has been called in a specific namespace, it's absolutely feasible for the param to have been set in the same one.

**Comment by davetcoleman** [comment]
I see your point and I agree this should be fixed. The question now is if this is a change that would break other's setup in Hydro who are loading their robot in a namespace but keeping their URDF on the root of the parameter server. 

I believe there is a rosparam method that recursively checks backwards in namespaces until it reaches the root. Implementing that change might be backwards compatible enough to be allowed into ROS Hydro. @hsu ?

**Comment by hsu** [comment]
Yes, maybe something similar to pull request #105 could be used.

**Comment by davetcoleman** [comment]
Yep, `searchParam()`

**Comment by j-rivero** [comment]
Fixed.

**Comment by jay3ss** [comment]
This issue seems to be popping up again: https://answers.ros.org/question/268655/gazebo_ros_control-plugin-is-waiting-for-model-urdf-in-parameter/

**Comment by j-rivero** [comment]
> This issue seems to be popping up again: https://answers.ros.org/question/268655/gazebo_ros_control-plugin-is-waiting-for-model-urdf-in-parameter/

Thanks for the warning. I've checked the kinetic-devel branch and the changes in pull request #134 and they are present in the kinetic-devel branch, probably from the beginning.

**Comment by jay3ss** [comment]
I'm on Kinetic and Indigo and have gotten it on both

**Comment by phyatt16** [comment]
I also am still having this problem.

**Comment by rahulgupta582** [comment]
Hi,

I'm using ROS melodic. multimaster_fkie.

getting "gazebo_ros_control plugin is waiting for model URDF in parameter [/jackal/robot_description] on the ROS param server."

Also suggest me how can i pass this URDF in parameter on ROS param server?

-------------------------These are the logs from docker terminal------------------------

Finished loading Gazebo ROS API Plugin. waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting... Finished loading Gazebo ROS API Plugin. waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting... waitForService: Service [/gazebo/set_physics_properties] is now available. Physics dynamic reconfigure ready. Camera Plugin: Using the 'robotNamespace' param: 'jackal/front_stereo/' Camera Plugin: Using the 'robotNamespace' param: 'jackal/front_stereo/' Camera Plugin (ns = jackal/front_stereo/) <tf_prefix_>, set to "jackal/front_stereo" Camera Plugin (ns = jackal/front_stereo/) <tf_prefix_>, set to "jackal/front_stereo" Loading gazebo_ros_control plugin Starting gazebo_ros_control plugin in namespace: jackal gazebo_ros_control plugin is waiting for model URDF in parameter [/jackal/robot_description] on the ROS param server.
