### ISSUE TITLE
Unable to locate package ros-foxy-gazebo-ros-pkgs  Raspberry Pi4 20.04 Ubuntu

### ISSUE THREAD

**Issue by MarcoAndrade26** [ros-simulation/gazebo_ros_pkgs#1158]
I am trying to install gazebo-ros-pakgs running the following commands on Ubuntu 20.04:
sudo apt update
sudo apt upgrade
sudo apt install python3-colcon-common-extensions
sudo apt install gazebo11 libgazebo11-dev

But when running:
sudo apt install ros-foxy-gazebo-ros-pkgs

It shows me the error: E: Unable to locate package ros-foxy-gazebo-ros-pkgs

I tried also with:
sudo apt install gazebo11 ros-foxy-gazebo-ros-pkgs

But I am getting the same error.

**Environment:**

 - Board: Raspberry Pi4 4Gb of RAM
 - OS: Ubuntu 20.04
 - Gazebo version: Gazebo11
 - ROS version: Foxy
 - gazebo_ros_pkgs: Debian install

**Additional context**

Add any other context here.

**Comment by j-rivero** [comment]
Have you installed ROS2 before trying to install the foxy packages? Could be that you don't have the ROS2 repositories available.

**Comment by MarcoAndrade26** [comment]
I have already installed ROS2 and source it

**Comment by j-rivero** [comment]
may I have your output from:

```
sudo apt-get update
```
and
```
apt-cache search ros-foxy-gazebo*
```

**Comment by mrunaljsarvaiya** [comment]
I actually have the exact same issue. I've installed ros foxy on a Rpi4 running Ubuntu 20.04

Output after running `sudo apt-get update`:

```
Hit:1 http://packages.osrfoundation.org/gazebo/ubuntu-stable focal InRelease
Hit:2 http://packages.ros.org/ros/ubuntu focal InRelease            
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal InRelease          
Hit:4 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu focal InRelease
Hit:5 http://packages.ros.org/ros2/ubuntu focal InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:7 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Reading package lists... Done
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target CNF (main/cnf/Commands-arm64) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target CNF (main/cnf/Commands-arm64) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/ros-focal.list:1 and /etc/apt/sources.list.d/ros-latest.list:1
```

Output after running `apt-cache search ros-foxy-gazebo*`:
```
ros-foxy-gazebo-dev - Provides a cmake config for the default version of Gazebo for the ROS distribution.
ros-foxy-gazebo-msgs - Message and service data structures for interacting with Gazebo from ROS2.
ros-foxy-gazebo-msgs-dbgsym - debug symbols for ros-foxy-gazebo-m
```

**Comment by chapulina** [comment]
> Board: Raspberry Pi4 4Gb of RAM

> ros foxy on a Rpi4

This is the problem, `gazebo-ros-pkgs` is only available for amd64:

http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-foxy-gazebo-ros-pkgs/

**Comment by MarcoAndrade26** [comment]
@chapulina Thanks! Does anyone know how to disable Gazebo when building Navigation2?

**Comment by j-rivero** [comment]
> This is the problem, `gazebo-ros-pkgs` is only available for amd64:

Checking the root of the problem for this, I see _arm64 packages name in http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-foxy-gazebo-ros-pkgs/ dated on 09/04.

If I'm not wrong, this is the tracker for arm64 builds: http://repo.ros2.org/status_page/ros_foxy_ubv8.html?q=gazebo_ros_pkgs

**Comment by samuk** [comment]
Predictably this is still an issue on Humble/ Pi4

**Comment by j-rivero** [comment]
> Predictably this is still an issue on Humble/ Pi4

Not probably the same problem since platforms changed from Foxy to Humble. Humble is probably affected by https://github.com/osrf/gazebo/issues/3236, please follow the issue there.

Thanks.
