### ISSUE TITLE
[ROS2] Hand of God Plugin Failing on ros2 branch

### ISSUE THREAD

**Issue by SteveMacenski** [ros-simulation/gazebo_ros_pkgs#1178]
**Description**

ROS2 branch is failing due to a potential change or lack of header in the word of god plugin. We found this in Navigation2's CI which uses your `ros2` branch to build against. See CI link below for specific error, but `/opt/underlay_ws/src/ros-simulation/gazebo_ros_pkgs/gazebo_plugins/src/gazebo_ros_hand_of_god.cpp:75:28: error: ‘Buffer’ is not a member of ‘tf2_ros’` is the root cause.  It looks like tf2_ros had some changes a few days ago that broke this. 

**To Reproduce**

https://app.circleci.com/pipelines/github/ros-planning/navigation2/3970/workflows/72b4873d-9e62-4302-b1d7-d02c70453b47/jobs/15279

```
git@github.com:ros-simulation/gazebo_ros_pkgs.git -b ros2

colcon build 
```

**Expected behavior**

Builds correctly :wink:

**Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - Gazebo version: N/A
 - ROS version: master
  - gazebo_ros_pkgs: ros2 branch
 - glx server in use: N/A

**Comment by scpeters** [comment]
closed by #1179
