### ISSUE TITLE
Gazebo Ros Projector Build Error

### ISSUE THREAD

**Issue by ghost** [ros-simulation/gazebo_ros_pkgs#122]
I'm building ROS Hydro on Debian Wheezy,and am getting build errors. I have built gazebo from source and installed it with my package manager. In this issue make is unable to find Rendering.hh because it was named differently in gazebo's include library.

$ cd /home/peter/Documents/ros_workspace/build_isolated/gazebo_plugins && /home/peter/Documents/ros_workspace/hydro/env.sh make -j4 -l4 --debug=v 
...
/home/peter/Documents/ros_workspace/src/gazebo_plugins/src/gazebo_ros_projector.cpp:29:41: fatal error: gazebo/rendering/Rendering.hh: No such file or directory
compilation terminated.
make[2]: **\* [CMakeFiles/gazebo_ros_projector.dir/src/gazebo_ros_projector.cpp.o] Error 1
make[1]: **\* [CMakeFiles/gazebo_ros_projector.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
make: **\* [all] Error 2

 $sudo find / -name "*endering.hh" -type f
/usr/local/include/gazebo-1.9/gazebo/rendering/rendering.hh
/home/peter/Documents/ros_workspace/external_src/gazebo/gazebo/rendering/rendering.hh

$ find /home/peter/Documents/ros_workspace/build_isolated/gazebo_plugins -type f -exec grep Rendering.hh {} +
/home/peter/Documents/ros_workspace/build_isolated/gazebo_plugins/CMakeFiles/gazebo_ros_projector.dir/CXX.includecache:gazebo/rendering/Rendering.hh

$ find / -type f -exec grep Rendering.hh {} +
/home/peter/Documents/ros_workspace/build_error:/home/peter/Documents/ros_workspace/build_isolated/gazebo_plugins/CMakeFiles/gazebo_ros_projector.dir/CXX.includecache:gazebo/rendering/Rendering.hh
/home/peter/Documents/ros_workspace/build_error:/home/peter/Documents/ros_workspace/src/gazebo_plugins/src/gazebo_ros_projector.cpp:29:41: fatal error: gazebo/rendering/Rendering.hh: No such file or directory
/home/peter/Documents/ros_workspace/src/gazebo_plugins/src/gazebo_ros_projector.cpp:#include <gazebo/rendering/Rendering.hh>

The fix is:
cp /usr/local/include/gazebo-1.9/gazebo/rendering/rendering.hh /usr/local/include/gazebo-1.9/gazebo/rendering/Rendering.hh

This is how I installed gazebo (9/28/2013):
hg clone https://bitbucket.org/osrf/gazebo gazebo
cd gazebo
cmake .
sudo checkinstall make install

Either gazebo needs to install that file as Rendering.hh or gazebo_ros_projector.cpp needs to include rendering.hh instead. I'm new to this process so I'm not sure how implement the fix myself.

**Comment by scpeters** [comment]
Are you using an older version of gazebo_ros_pkgs? The include reference was changed to `gazebo/rendering/RenderingIface.hh` in b52d6bfcb9a786f1b239369d5c06607b204c5d5e

**Comment by ghost** [comment]
I pulled everything with wstool 2 days ago with:
$ rosinstall_generator desktop_full --rosdistro hydro --deps --wet-only > hydro-desktop-full-wet.rosinstall
$ wstool init -j8 src hydro-desktop-full-wet.rosinstall
Your correct though, that file exists in the 1.9 gazebo release, so the change must not have made its way into the source yet. Thanks for your help, I'll post that fix in my install instructions so it isn't mistaken again.
