### ISSUE TITLE
gazebo_ros_control: controlPeriod greater than the simulation period causes unexpected results.

### ISSUE THREAD

**Issue by jim-rothrock** [ros-simulation/gazebo_ros_pkgs#125]
I am running my Gazebo simulation at 1 kHz. This seems like overkill for my effort-based joint position and velocity controllers (servos often use a 50 Hz PID loop), so I set the gazebo_ros_control control frequency to 100 Hz, like this:

<pre>
  &lt;xacro:property name="ctrl_period" value="0.01"/&gt;

  &lt;gazebo&gt;
    &lt;plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"&gt;
      &lt;controlPeriod&gt;${ctrl_period}&lt;/controlPeriod&gt;
    &lt;/plugin&gt;
  &lt;/gazebo&gt;
</pre>

This caused my simulated vehicle's shock absorbers to stop working, and its steering to become sluggish. I mitigated (but didn't completely fix) the problem by making this modification to gazebo_ros_control_plugin.cpp:

<pre>
void GazeboRosControlPlugin::Update()
{
  // Get the simulation time and period
  gazebo::common::Time gz_time_now = parent_model_->GetWorld()->GetSimTime();
  ros::Time sim_time_ros(gz_time_now.sec, gz_time_now.nsec);
  ros::Duration sim_period = sim_time_ros - last_sim_time_ros_;

#ifdef NOTDEF
  // Check if we should update the controllers
  if(sim_period >= control_period_) {
    // Store this simulation time
    last_sim_time_ros_ = sim_time_ros;

    // Update the robot simulation with the state of the gazebo model
    robot_hw_sim_->readSim(sim_time_ros, sim_period);

    // Compute the controller commands
    controller_manager_->update(sim_time_ros, sim_period);

    // Update the gazebo model with the result of the controller
    // computation
    robot_hw_sim_->writeSim(sim_time_ros, sim_period);
  }
#else
  robot_hw_sim_->readSim(sim_time_ros, ros::Duration(0.001));

  if (sim_period >= control_period_)
  {
    last_sim_time_ros_ = sim_time_ros;
    controller_manager_->update(sim_time_ros, sim_period);
  }

  robot_hw_sim_->writeSim(sim_time_ros, ros::Duration(0.001));
#endif
}
</pre>

It seems as if the original code and the replacement I wrote should be roughly equivalent. My hypothesis is that the SetForce() calls in DefaultRobotHWSim::writeSim() affect Gazebo's current time step only. However, I've found no SetForce() documentation that describes that behavior.

For the moment, I'm going to refrain from setting controlPeriod in my URDF file, so readSim(), update, and writeSim() will be called during each Gazebo time step. I'm posting this issue in case someone wants to investigate it.

**Comment by scpeters** [comment]
I'm a gazebo developer, and SetForce() affects Gazebo's current time step only. I'll just filed an issue regarding the SetForce() documentation.

https://bitbucket.org/osrf/gazebo/issue/878/joint-setforce-documentation-incomplete

**Comment by hsu** [comment]
agreed, [writeSim](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/gazebo_ros_control_plugin.cpp#L214) should be called at every time step, i.e. it should be moved outside of [this time step check](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/gazebo_ros_control_plugin.cpp#L202) so control force is applied at every simulation step.

**Comment by davetcoleman** [comment]
@hsu that sounds right, should be a simple fix
