### ISSUE TITLE
Please release noetic-devel

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros-simulation/gazebo_ros_pkgs#1262]
The use of `tf_prefix` is a bit of a mess. Some has been fixed in #1143, also #1173 is still open. Please merge #1173 and create a new release for noetic-devel.

I am not able to get my setup working without these changes. And I don't like to compile everything from source.

**Comment by MatthijsBurgh** [comment]
@j-rivero friendly ping ;)

**Comment by j-rivero** [comment]
> @j-rivero friendly ping ;)

friendly pong. I go for it, thanks @MatthijsBurgh

**Comment by j-rivero** [comment]
done, feel free to reopen if problems appear
