### ISSUE TITLE
foxy has no libgazebo_ros_openni_kinect

### ISSUE THREAD

**Issue by yuan-ge** [ros-simulation/gazebo_ros_pkgs#1369]
I have checked the foxy branch and found that this devel has no libgazebo_ros_openni_kinect, so is that a negligence? If not, what should I do to substitute it?

**Comment by KhairulM** [comment]
use libgazebo_ros_camera.so instead, i see this being used in the depth camera world example

**Comment by yuan-ge** [comment]
Thank you for reminding this, I also saw the related comment in the libgazebo_ros_camera.cpp. The tutorials in gazebo is old version.
