### ISSUE TITLE
NO gazebo_ros_openni_kinect.cpp in /opt/ros/melodic

### ISSUE THREAD

**Issue by chiawenwang** [ros-simulation/gazebo_ros_pkgs#1370]
I'm new to ROS and I'm confused with the DEBUG publishing message when I use the kinect camera in ROS as following:

![Screenshot from 2022-04-20 13-34-23](https://user-images.githubusercontent.com/80686289/164157505-a727b113-291e-4976-9fbe-1efeb54090e6.png)

I DO want to stop the DEBUG message and I think what I need to do is deleting the **[ROS_DEBUG]("publishing default camera info, then openni kinect camera info");**

But I can't find the relatived gazebo_ros_openni_kinect.cpp  but only the libgazebo_ros_openni_kinect.so in /opt/ros/melodic/lib

How can I deal with this problem?or maybe some tutorials about it?

**Comment by quarkytale** [comment]
You can use the [ROS rqt_logger_level](http://wiki.ros.org/rqt_logger_level) tool to disable all debug messages.
Also, the `gazebo_ros_openni_kinect.cpp` can't find the file probably because it's a binary installation. To view source files, [install from source](http://wiki.ros.org/noetic/Installation/Source) or checkout on [github](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/noetic-devel/gazebo_plugins/src/gazebo_ros_openni_kinect.cpp)!

**Comment by Gaviiin-W** [comment]
Thank u ,**quarkytale**!
I used the rqt_logger_level before and that quite worked.But I need to set the rqt_logger_level every time I roslaunch it.Is it possible to configure it?

**Comment by chiawenwang** [comment]
> You can use the [ROS rqt_logger_level](http://wiki.ros.org/rqt_logger_level) tool to disable all debug messages. Also, the `gazebo_ros_openni_kinect.cpp` can't find the file probably because it's a binary installation. To view source files, [install from source](http://wiki.ros.org/noetic/Installation/Source) or checkout on [github](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/noetic-devel/gazebo_plugins/src/gazebo_ros_openni_kinect.cpp)!

Thank u ,**quarkytale**!
I used the rqt_logger_level before and that quite worked.But I need to set the rqt_logger_level every time I roslaunch it.Is it possible to configure it?

**Comment by quarkytale** [comment]
This should help configuring what you need: [rosconsole](http://wiki.ros.org/rosconsole#Configuration). I'll suggest checking out [ROS Answers](https://answers.ros.org/questions/) too. Hope it helps!
