### ISSUE TITLE
Release Humble

### ISSUE THREAD

**Issue by SteveMacenski** [ros-simulation/gazebo_ros_pkgs#1399]
Hi,

I know Gazebo isn't officially supported, but it would be nice to have these released to Humble as the last distribution so the migration to Ignition can be less stressful and give us time to migrate over during the distribution.

Right now, this is the only major blocker for getting Nav2 released. Gazebo is being released by Debian so if these can work with that version, it would be much appreciated and let us move to get Nav2 and related projects to users sooner. Plus if we think of Gazebo as an external library, it's lack of support shouldn't prevent downstream packages from being released for its users

**Comment by jpvr20** [comment]
@SteveMacenski Hello, why was this closed? I'm currently trying to build this package in humble and gazebo garden, facing issues with it.

**Comment by mjcarroll** [comment]
@jpvr20 This repo is for Gazebo classic.  If you are looking to use Gazebo garden, you probably want https://github.com/gazebosim/ros_gz

**Comment by jpvr20** [comment]
@mjcarroll oh my bad, thank you! I stumbled here trying to make `libgazebo_ros_state` pluign work in gazebo garden world, looks like I need something else.
