### ISSUE TITLE
Launch parameter errors in gzserver.launch.py

### ISSUE THREAD

**Issue by scpeters** [ros-simulation/gazebo_ros_pkgs#1411]
I'm seeing some weird console errors using the `ros2` branch with the following launch command:

~~~
$ ros2 launch gazebo_ros gzserver.launch.py verbose:=true physics:=ode
...
[Err] [Server.cc:472] Could not open file[]
[Wrn] [Server.cc:381] Falling back on worlds/empty.world
...
[Err] [Server.cc:530] Unregistered physics engine [ ], the default will be used instead
~~~

**Comment by jacobperron** [comment]
Reverting https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1376 seems to resolve the issue.
I haven't looked too closely at what we can do to avoid using `shell=True` while avoiding these noisy console errors at the same time.

**Comment by jacobperron** [comment]
This was fixed in https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1414
