### ISSUE TITLE
Service %s/spawn_entity unavailable.

### ISSUE THREAD

**Issue by dvogureckiy99** [ros-simulation/gazebo_ros_pkgs#1473]
I use:
ubuntu 20.04
ros2 humble

After command `ros2 run gazebo_ros spawn_entity.py -entity solo12dof_quadruped -file ~/git/robot_programming_course/catkin_ws/src/solo12dof_quadruped/urdf/solo12dof_quadruped.urdf -x 0 -y 0 -z 1`:
```
[ERROR] [1680614010.466277126] [spawn_entity]: Service %s/spawn_entity unavailable. Was Gazebo started with GazeboRosFactory?
[ERROR] [1680614010.467486099] [spawn_entity]: Spawn service failed. Exiting.
```

**Comment by chngdickson** [comment]
Ros_gz_sim's implementation seems to be working.

`ros2 run ros_gz_sim create -file my_model.sdf -name new_name_for_model -x 0.1 -y 0.0 -z 2.0`
