### ISSUE TITLE
skip expanding package:// into full path

### ISSUE THREAD

**Issue by hsu** [ros-simulation/gazebo_ros_pkgs#153]
Skip [this](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros/src/gazebo_ros_api_plugin.cpp#L549) now that gazebo automatically loads sdf too.  Prevents expanding mesh from `package://*` uri to local file path.

**Comment by j-rivero** [comment]
There are use cases where not using the absolute path is useful.

**Comment by scpeters** [comment]
This seems related to #288
