### ISSUE TITLE
Broken document links

### ISSUE THREAD

**Issue by protonnet** [ros-simulation/gazebo_ros_pkgs#1547]
Hello, the link to the documentation can't be opened. Where else can I consult the documentation and tutorials?

Best1

**Comment by ahcorde** [comment]
PR updating the links https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1548

Anyhow I recomend you to start using the new gazebo https://gazebosim.org/. Gazebo classic will be end of life soon.
