### ISSUE TITLE
gazebo_plugins - gazebo_ros_imu: Frame id not in ROS format

### ISSUE THREAD

**Issue by martimorta** [ros-simulation/gazebo_ros_pkgs#159]
Hi,
I have a model in SDF and I am using the IMU plugin gazebo_ros_imu in gazebo_plugins.
In the model the bodylink is "robot::imu", then there is a problem with the IMU topic's frame_id which is in SDF format (the ::) instead of robot/imu.
Maybe change "::" for "/" would solve this.

Thanks in advance!

**Comment by j-rivero** [comment]
Hey Marti!

Do you know if the bug is still present in the latest versions of ROS? If so, could you please provide an example to reproduce it?

**Comment by martimorta** [comment]
Hello hello,
I don't know to be honest, I suppose if no one else has complained in 2 years it would have been fixed at some point.
I can't reproduce that error but the simulation was the one for Teo, I think for Gazebo 2, [teo_sim](https://devel.iri.upc.edu/pub/labrobotica/ros/iri-ros-pkg_hydro/metapackages/teo_robot/teo_sim/)
In teo.sdf line 234 there's the call to the imu:

``` xml
<plugin name="imu_controller" filename="libgazebo_ros_imu.so">
      <bodyName>teo::imu</bodyName>
      <robotNamespace>/teo</robotNamespace>
      <serviceName>/teo/imu/calibrate</serviceName>
      <topicName>/teo/sensors/imu</topicName>
      <gaussianNoise>0.03</gaussianNoise>
      <xyzOffset>0 0 0</xyzOffset>
      <rpyOffset>0 0 0</rpyOffset>
    </plugin>
```

I am not sure that would help but I can't say much more :S

**Comment by kev-the-dev** [comment]
This is due to the _default_ behavior for frame_id to be the link name. However, most users override this by setting the <frameName> flag in the sdf. Example:
```
<plugin name="imu_controller" filename="libgazebo_ros_imu.so">
      <bodyName>teo::imu</bodyName>
      <robotNamespace>/teo</robotNamespace>
      <serviceName>/teo/imu/calibrate</serviceName>
      <topicName>/teo/sensors/imu</topicName>
      <gaussianNoise>0.03</gaussianNoise>
      <xyzOffset>0 0 0</xyzOffset>
      <rpyOffset>0 0 0</rpyOffset>
      <!-- frame_id in the header of /teo/sensors/imu will be "my_imu" -->
      <frameName>my_imu</frameName>
</plugin>
```
