### ISSUE TITLE
Document usage of gazebo_ros_paths plugin

### ISSUE THREAD

**Issue by jonbinney** [ros-simulation/gazebo_ros_pkgs#160]
This plugin is very useful, but I don't see it mentioned here:
http://gazebosim.org/wiki/Tutorials/1.9/Using_roslaunch_Files_to_Spawn_Models#Creating_your_own_Gazebo_ROS_Package

Would it make sense to add a section "Setting gazebo paths from ROS packages"? The useful info would be the format for exporting model paths from a package.xml:

```
  <export>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
    <gazebo_ros gazebo_media_path="${prefix}/models"/>
  </export>
```

The '${prefix}` is something that new users might not immediately know about either, and necessary here.

Also would be useful to have some info on how to debug these paths from the ROS side, e.g. that you can use `rospack plugins --attrib="gazebo_media_path" gazebo_ros` To check the media path that will be picked up by gazebo.

When I started using gazebo and ROS together, I didn't realize that the gazebo_ros_paths plugin existed, and spent a while doing things the hard way with custom shell scripts and cmake macros.

**Comment by abcgarden44** [comment]
I totally agree with you. I also had spent some time on this and finally found out this answer. Why not write this into gazebosim.org tutorial immediately?

**Comment by scpeters** [comment]
We accept pull requests for gazebo tutorials at bitbucket:
- https://bitbucket.org/osrf/gazebo_tutorials/src/1f9391c953c014669f417f5e188d4b171b49f91b/ros_roslaunch/tutorial.md?at=default

**Comment by hsu** [comment]
[gazebo_tutorials issue created](https://bitbucket.org/osrf/gazebo_tutorials/issue/28/update-ros_launch-tutorial-to-include), can we migrate discussion over there?

**Comment by k-okada** [comment]
added comment above to  https://bitbucket.org/osrf/gazebo_tutorials/pull-requests/279/document-usage-of-gazebo_ros_paths-plugin/diff#chg-ros_roslaunch/tutorial.md

**Comment by 130s** [comment]
[The PR at Gazebo tutorial](https://bitbucket.org/osrf/gazebo_tutorials/pull-requests/279/document-usage-of-gazebo_ros_paths-plugin/diff#chg-ros_roslaunch/tutorial.md) is merged. This ticket can now  be closed.

**Comment by jonbinney** [comment]
Awesome. Thanks guys!

**Comment by cyborg-x1** [comment]
Hi, I came across cause I got a question on that, so you have done this tutorial maybe you have an idea how I can get this to work:

http://answers.ros.org/question/257694/questions-to-sdf-urdf-xacro-material-textures-using-gazebo/
