### ISSUE TITLE
gazebo_ros_multicamera plugin: left camera has wrong namespace

### ISSUE THREAD

**Issue by jordi-pages** [ros-simulation/gazebo_ros_pkgs#161]
I am defining a stereo camera in a urdf as follows:

```
<gazebo reference="${name}_link">
  <sensor type="multicamera" name="gazebo_${name}_camera">
    <update_rate>25.0</update_rate>
    <camera name="left">
      <horizontal_fov>${ hfov }</horizontal_fov>
      <image>
        <width>${image_width} </width>
        <height> ${image_height}</height>
        <format>${image_format}</format>
      </image>
      <clip>
        <near>0.01</near>
        <far>100</far>
      </clip>
    </camera>
<camera name="right">
      <pose>0 -${hack_baseline} 0 0 0 0</pose>
      <horizontal_fov>${ hfov }</horizontal_fov>
      <image>
        <width>${image_width} </width>
        <height> ${image_height}</height>
        <format>${image_format}</format>
     </image>
     <clip>
       <near>0.01</near>
       <far>100</far>
     </clip>
   </camera>
   <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
     <alwaysOn>true</alwaysOn>
     <updateRate>25.0</updateRate>
     <cameraName>${name}</cameraName>
     <imageTopicName>image</imageTopicName>
     <cameraInfoTopicName>camera_info</cameraInfoTopicName>
     <frameName>${frame_id}</frameName>
     <hackBaseline>${hack_baseline}</hackBaseline>
     <CxPrime>${(image_width+1)/2}</CxPrime>
     <Cx>${(image_width+1)/2}</Cx>
     <Cy>${(image_height+1)/2}</Cy>
     <focalLength>${focal_length}</focalLength> <!-- image_width / (2*tan(hfov_radian /2)) -->
     <distortionK1>0.0</distortionK1>
     <distortionK2>0.0</distortionK2>
     <distortionK3>0.0</distortionK3>
     <distortionT1>0.0</distortionT1>
     <distortionT2>0.0</distortionT2>
  </plugin>
</sensor>
```

  </gazebo>

the expected ROS topic for the camera are:

/stereo/left/camera_info
/stereo/left/image
/stereo/right/camera_info
/stereo/right/image

Unfortunately, most of the times I launch gazebo the topics are:

/stereo/camera_info
/stereo/image
/stereo/right/camera_info
/stereo/right/image

where the left camera namespace does not appear correctly. The most strange thing is that from time to time gazebo launches properly and the right camera namespace appear. No error message appears during gazebo start up.

**Comment by j-rivero** [comment]
I believe that we have been using the multicamera plugin extensively during the DRC developement and I've never found this problem before, so probably we have a workaround in place, a different approach or I'm plain wrong.

@hsu what could be the case?

**Comment by hsu** [comment]
I have not seen it either, for reference, a multicamera example is found [here](https://bitbucket.org/osrf/drcsim/src/52a691b8956045442ef22ba0aaee4520716807ff/multisense_sl_description/urdf/multisense_sl.urdf?at=default#cl-200), and [here's the corresponding stereo_image_proc](https://bitbucket.org/osrf/drcsim/src/52a691b8956045442ef22ba0aaee4520716807ff/drcsim_gazebo/launch/atlas_bringup.launch?at=default#cl-38).

Which version/flavor of `gazebo_ros_pkgs` are you using?

**Comment by jordi-pages** [comment]
Sorry for the delay. I am working with the hydro-devel branch of gazebo_ros_pkgs. By adding a simple sleep in the appropriate place you should be able to reproduce the problem, see https://github.com/jordi-pages/gazebo_ros_pkgs/commit/fb0250cafaf8899398ed0faa20ffdbf5bf6d3eb8

with such sleep I get both cameras publishing in /stereo/image. The cause is that GazeboRosCameraUtils::LoadThread() is run before the last instruction in GazeboRosCameraUtils::Load() which appends the camera name suffix.

**Comment by j-rivero** [comment]
Using our drcsim atlas simulation and your sleep trick I was not able to reproduce the bug, the topic namespaces are correct. 

Jordi, could you quickly provide a repository with a URDF and a ROS launch that we can use to reproduce the issue? thanks.

**Comment by j-rivero** [comment]
I spoke with John yesterday, he was able to reproduce the fail after several tries. I'm fine with the merge and the release. Thanks Jordi.

**Comment by jordi-pages** [comment]
Ok, thanks a lot to both you
