### ISSUE TITLE
Consider adding sonar or infrared sensor plugins

### ISSUE THREAD

**Issue by hsu** [ros-simulation/gazebo_ros_pkgs#162]
Inspired by [this pose](http://answers.gazebosim.org/question/5303/is-there-a-gazebo-plugin-that-simulates-sonar-and/?answer=5354#post-id-5354).

Consider moving plugin from [pal_gazebo_plugin](https://github.com/pal-robotics/pal_gazebo_plugins/blob/hydro-devel/src/gazebo_ros_range.cpp) here.

Also, potentially add a new ROS plugin for the [sonar implementation in gazebo](https://bitbucket.org/osrf/gazebo/src/b1dea9012cb37b5afc2336fce5d9f30e7cbc475f/gazebo/sensors/SonarSensor.cc?at=default).

**Comment by AlexReimann** [comment]
Fork with only the ros range message gazebo plugin (without dependencies on other pal stuff for quick tryout):  https://github.com/AlexReimann/pal_gazebo_plugins

Should I make pull request to add this to the gazebo plugin packages?

@po1 Could you confirm if the gazebo_ros_range plugin is stable?

**Comment by jack-oquin** [comment]
+1

**Comment by bit-pirate** [comment]
+1

Ping @adolfo-rt

**Comment by bmagyar** [comment]
+1 from me, and for the question of stability, yes, we've been using this ever since the copyright notice (2013)

**Comment by adolfo-rt** [comment]
+1 for the feature, which means rebasing #311 against at least `indigo-devel`.

**Comment by j-rivero** [comment]
Thanks to the friends of Pal this is now implemented.
