### ISSUE TITLE
"No matching hardware interface found for 'PositionJointInterface"

### ISSUE THREAD

**Issue by costashatz** [ros-simulation/gazebo_ros_pkgs#163]
I was able to run examples using PositionJointInterface as hardware interface with no problems if I **build ros_control and gazebo_ros_pkgs in the catkin workspace.**
However, _the deb packages don't seem to work even after updating to latest version_ (meaning 0.6.0 for ros_control and 2.3.4 for gazebo_ros_pkgs)..
I get something like that:

```
[FATAL] [1392109605.812461357, 1.596000000]: No matching hardware interface found for 'PositionJointInterface
```

I also get:

```
[ INFO] [1392109605.806446504, 1.596000000]: pluginlib WARNING: In file /tmp/buildd/ros-hydro-gazebo-ros-control-2.3.4-0raring-20140205-0108/src/default_robot_hw_sim.cpp PLUGINLIB_DECLARE_CLASS is deprecated, please use PLUGINLIB_EXPORT_CLASS instead.
```

I am running _Xubuntu 13.04 and 12.04_ and the **problem exists in both.**

Any ideas?

**Comment by adolfo-rt** [comment]
This is expected behavior.

Support for position and velocity interfaces was added in PR #135. The current 2.3.4 release predates this PR, hence does not contain it. The next release should have it, though. Until then building from source is the way to go.
