### ISSUE TITLE
No p gain specified for pid in PositionJointInterface

### ISSUE THREAD

**Issue by costashatz** [ros-simulation/gazebo_ros_pkgs#164]
I have built gazebo_ros_pkgs in the catkin workspace and working with some Joint Position Controllers (successfully - I can control my joint controllers via rqt or topics).

However, my robot keeps sliding on the ground (slowly but sliding). Here's a video of that [behavior](https://dl.dropboxusercontent.com/u/108830475/out.ogv). At first I thought it was because I hadn't included friction on my links. I did include friction but nothing changed. Also, at first I had collada models for collision, but changed them to stl. Same behavior though. I suspect visual-collision misalignment (exists in my case) problems in gazebo.

Gazebo throws some errors (not fatal ones though and continues). Here's an example:

```
[ERROR] [1392128262.341496657, 0.791000000]: No p gain specified for pid.  Namespace: /nao_robot/gazebo_ros_control/pid_gains/RAnklePitch_Roll_Joint
```

I haven't created effort joint controllers as the robot I'm trying to simulate has servo motors. I am not sure if that is entirely correct. Maybe I need effort joint controllers.

Any ideas? Thanks..

**Comment by adolfo-rt** [comment]
The position control interface has two ways of working:
- If you specify a set of PID gains for the joints, a PID controller will be set up to convert joint position commands to joint efforts.
- If no PIDs are specified, joint dynamics are ignored and a purely kinematic motion is realized (ie. allowing for discrete jumps).

The error message you're getting suggests that you don't have a joint PID spec, and that joint dynamics are being ignored.

**Comment by costashatz** [comment]
And how is this connected to the sliding of the robot?

**Comment by adolfo-rt** [comment]
> And how is this connected to the sliding of the robot?

I'm providing an explanation for the bits I know. I don't have enough information to make a judgment on the sliding part. It can depend on the controllers you have running, their configuration, the mass distribution of your robot, contact point dynamics, the list goes on.

I think that gazebo answers is a better place for asking about the sliding problem. You have a better chance of getting a satisfactory response there.

**Comment by adolfo-rt** [comment]
Moved to [Gazebo answers](http://answers.gazebosim.org/question/5468/gazebo_ros_pkgs-no-p-gain-specified-for-pid-in/?answer=5470#post-id-5470).
