### ISSUE TITLE
Try to drop dependency on pcl_conversions

### ISSUE THREAD

**Issue by scpeters** [ros-simulation/gazebo_ros_pkgs#178]
There is an open pull request ( https://github.com/ros/common_msgs/pull/16 ) that may allow us to drop our dependency on pcl_conversions, since we only appear to use pcl_conversions to manipulate ros messages.

See [gazebo_ros_depth_camera.cpp:249-279](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_plugins/src/gazebo_ros_depth_camera.cpp#L249-L279) and [gazebo_ros_openni_kinect.cpp:304-377](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_plugins/src/gazebo_ros_openni_kinect.cpp#L304-L377)

@wjwwood

**Comment by j-rivero** [comment]
done.
