### ISSUE TITLE
Ubuntu 12.10 freeze when starting gazebo with pr2

### ISSUE THREAD

**Issue by b2220333** [ros-simulation/gazebo_ros_pkgs#187]
This is a critical issue that we can use ROS or not, because we need to use 3D simulator heavily.
I use ubuntu 12.10 with ROS groovy.
When I run roslaunch pr2_gazebo pr2_empty_world.launch, the whole computer freeze.
I can't move mouse or type on keyboard.
I use the video card driver with additional drivers.
How to fixed it?
Thank you~

**Comment by b2220333** [comment]
I attach /var/log/kern.log ( I use another linux system to mount into)
sam@sam:/media/ebee5541-bbe5-42c2-91d6-664e1bb90c75/var/log$ tail -n 100 kern.log
Apr 24 16:31:17 sam kernel: [   14.469140] kvm: disabled by bios
Apr 24 16:31:17 sam kernel: [   14.521429] kvm: disabled by bios
Apr 24 16:31:17 sam kernel: [   14.544950] kvm: disabled by bios
Apr 24 16:31:17 sam kernel: [   15.060182] input: HDA NVidia HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input15
Apr 24 16:31:17 sam kernel: [   15.060359] input: HDA NVidia HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input16
Apr 24 16:31:17 sam kernel: [   15.060476] input: HDA NVidia HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input17
Apr 24 16:31:17 sam kernel: [   15.060591] input: HDA NVidia HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input18
Apr 24 16:31:17 sam kernel: [   15.819974] EXT4-fs (sda2): re-mounted. Opts: errors=remount-ro
Apr 24 16:31:17 sam kernel: [   15.926810] Bluetooth: Core ver 2.16
Apr 24 16:31:17 sam kernel: [   15.926824] NET: Registered protocol family 31
Apr 24 16:31:17 sam kernel: [   15.926825] Bluetooth: HCI device and connection manager initialized
Apr 24 16:31:17 sam kernel: [   15.926826] Bluetooth: HCI socket layer initialized
Apr 24 16:31:17 sam kernel: [   15.926826] Bluetooth: L2CAP socket layer initialized
Apr 24 16:31:17 sam kernel: [   15.926829] Bluetooth: SCO socket layer initialized
Apr 24 16:31:17 sam kernel: [   15.928292] Bluetooth: RFCOMM TTY layer initialized
Apr 24 16:31:17 sam kernel: [   15.928296] Bluetooth: RFCOMM socket layer initialized
Apr 24 16:31:17 sam kernel: [   15.928297] Bluetooth: RFCOMM ver 1.11
Apr 24 16:31:17 sam kernel: [   15.929189] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Apr 24 16:31:17 sam kernel: [   15.929191] Bluetooth: BNEP filters: protocol multicast
Apr 24 16:31:17 sam kernel: [   15.954655] ppdev: user-space parallel port driver
Apr 24 16:31:17 sam kernel: [   15.960394] type=1400 audit(1398328277.842:8): apparmor="STATUS" operation="profile_load" name="/usr/lib/cups/backend/cups-pdf" pid=1239 comm="apparmor_parser"
Apr 24 16:31:17 sam kernel: [   15.960638] type=1400 audit(1398328277.842:9): apparmor="STATUS" operation="profile_load" name="/usr/sbin/cupsd" pid=1239 comm="apparmor_parser"
Apr 24 16:31:17 sam kernel: [   15.992245] type=1400 audit(1398328277.874:10): apparmor="STATUS" operation="profile_replace" name="/sbin/dhclient" pid=1275 comm="apparmor_parser"
Apr 24 16:31:17 sam kernel: [   15.992368] type=1400 audit(1398328277.874:11): apparmor="STATUS" operation="profile_load" name="/usr/sbin/tcpdump" pid=1281 comm="apparmor_parser"
Apr 24 16:31:18 sam kernel: [   16.179871] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Apr 24 16:31:18 sam kernel: [   16.180496] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Apr 24 16:31:18 sam kernel: [   16.181836] tg3 0000:08:00.0: irq 85 for MSI/MSI-X
Apr 24 16:31:18 sam kernel: [   16.181841] tg3 0000:08:00.0: irq 86 for MSI/MSI-X
Apr 24 16:31:18 sam kernel: [   16.181856] tg3 0000:08:00.0: irq 87 for MSI/MSI-X
Apr 24 16:31:18 sam kernel: [   16.181859] tg3 0000:08:00.0: irq 88 for MSI/MSI-X
Apr 24 16:31:18 sam kernel: [   16.181863] tg3 0000:08:00.0: irq 89 for MSI/MSI-X
Apr 24 16:31:18 sam kernel: [   16.635537] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Apr 24 16:31:18 sam kernel: [   16.635707] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Apr 24 16:31:19 sam kernel: [   17.158163] vboxdrv: Found 12 processor cores.
Apr 24 16:31:19 sam kernel: [   17.158358] vboxdrv: fAsync=1 offMin=0xc5eb2ada offMax=0xc5eb2ada
Apr 24 16:31:19 sam kernel: [   17.158435] vboxdrv: TSC mode is 'asynchronous', kernel timer mode is 'normal'.
Apr 24 16:31:19 sam kernel: [   17.158436] vboxdrv: Successfully loaded version 4.3.4 (interface 0x001a0005).
Apr 24 16:31:19 sam kernel: [   17.364120] vboxpci: IOMMU not found (not registered)
Apr 24 16:31:19 sam kernel: [   17.376870] ipmi message handler version 39.2
Apr 24 16:31:19 sam kernel: [   17.379069] IPMI System Interface driver.
Apr 24 16:31:19 sam kernel: [   17.379107] ipmi_si: Adding default-specified kcs state machine
Apr 24 16:31:19 sam kernel: [   17.379109] ipmi_si: Trying default-specified kcs state machine at i/o address 0xca2, slave address 0x0, irq 0
Apr 24 16:31:19 sam kernel: [   17.379113] ipmi_si: Interface detection failed
Apr 24 16:31:19 sam kernel: [   17.404128] ipmi_si: Adding default-specified smic state machine
Apr 24 16:31:19 sam kernel: [   17.404131] ipmi_si: Trying default-specified smic state machine at i/o address 0xca9, slave address 0x0, irq 0
Apr 24 16:31:19 sam kernel: [   17.404134] ipmi_si: Interface detection failed
Apr 24 16:31:19 sam kernel: [   17.404210] ipmi_si: Adding default-specified bt state machine
Apr 24 16:31:19 sam kernel: [   17.404213] ipmi_si: Trying default-specified bt state machine at i/o address 0xe4, slave address 0x0, irq 0
Apr 24 16:31:19 sam kernel: [   17.404217] ipmi_si: Interface detection failed
Apr 24 16:31:19 sam kernel: [   17.404279] ipmi_si: Unable to find any System Interface(s)
Apr 24 16:31:21 sam kernel: [   19.322916] wlan0: authenticate with 00:0a:79:d1:8b:60
Apr 24 16:31:21 sam kernel: [   19.370361] wlan0: send auth to 00:0a:79:d1:8b:60 (try 1/3)
Apr 24 16:31:21 sam kernel: [   19.375852] wlan0: authenticated
Apr 24 16:31:21 sam kernel: [   19.404025] wlan0: associate with 00:0a:79:d1:8b:60 (try 1/3)
Apr 24 16:31:21 sam kernel: [   19.407636] wlan0: RX AssocResp from 00:0a:79:d1:8b:60 (capab=0x401 status=0 aid=2)
Apr 24 16:31:21 sam kernel: [   19.410654] wlan0: associated
Apr 24 16:31:21 sam kernel: [   19.411011] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
Apr 24 16:38:06 sam kernel: [  430.221177] usb 3-2: USB disconnect, device number 2
Apr 24 16:38:07 sam kernel: [  431.820080] phy0 -> rt2800_wait_wpdma_ready: Error - WPDMA TX/RX busy [0xffffffff].
Apr 24 16:38:07 sam kernel: [  431.820339] wlan0: deauthenticating from 00:0a:79:d1:8b:60 by local choice (reason=3)
Apr 24 16:38:07 sam kernel: [  431.824259] cfg80211: All devices are disconnected, going to restore regulatory settings
Apr 24 16:38:07 sam kernel: [  431.824266] cfg80211: Restoring regulatory settings
Apr 24 16:38:07 sam kernel: [  431.824271] cfg80211: Calling CRDA to update world regulatory domain
Apr 24 16:38:07 sam kernel: [  431.829832] cfg80211: Updating information on frequency 2412 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829838] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829841] cfg80211: Updating information on frequency 2417 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829845] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829847] cfg80211: Updating information on frequency 2422 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829850] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829853] cfg80211: Updating information on frequency 2427 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829856] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829859] cfg80211: Updating information on frequency 2432 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829862] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829864] cfg80211: Updating information on frequency 2437 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829867] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829870] cfg80211: Updating information on frequency 2442 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829873] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829875] cfg80211: Updating information on frequency 2447 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829878] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829881] cfg80211: Updating information on frequency 2452 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829884] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829887] cfg80211: Updating information on frequency 2457 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829890] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829892] cfg80211: Updating information on frequency 2462 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829895] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829898] cfg80211: Updating information on frequency 2467 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829901] cfg80211: 2457000 KHz - 2482000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829903] cfg80211: Updating information on frequency 2472 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829906] cfg80211: 2457000 KHz - 2482000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829909] cfg80211: Updating information on frequency 2484 MHz for a 20 MHz width channel with regulatory rule:
Apr 24 16:38:07 sam kernel: [  431.829912] cfg80211: 2474000 KHz - 2494000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829916] cfg80211: World regulatory domain updated:
Apr 24 16:38:07 sam kernel: [  431.829918] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
Apr 24 16:38:07 sam kernel: [  431.829921] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829924] cfg80211:   (2457000 KHz - 2482000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829927] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829929] cfg80211:   (5170000 KHz - 5250000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:38:07 sam kernel: [  431.829932] cfg80211:   (5735000 KHz - 5835000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Apr 24 16:39:03 sam kernel: [  487.633352] show_signal_msg: 57 callbacks suppressed
Apr 24 16:39:03 sam kernel: [  487.633356] gzserver[3643]: segfault at 4000000019 ip 00007fe13cd03be3 sp 00007fff2fa02970 error 4 in libOgreMain.so.1.7.4[7fe13cb8b000+4d0000]
sam@sam:/media/ebee5541-bbe5-42c2-91d6-664e1bb90c75/var/log$

**Comment by b2220333** [comment]
When ubuntu freezed, I plug and unplug Wireless network USB adapter to test, and I found that it didn't work anymore.
Here is the log of dmesg: ( I use another linux system to mount into)
sam@sam:/media/ebee5541-bbe5-42c2-91d6-664e1bb90c75/var/log$ tail -n 100 dmesg
[   14.149044] microcode: CPU8 sig=0x206d7, pf=0x4, revision=0x0
[   14.149754] microcode: CPU9 sig=0x206d7, pf=0x4, revision=0x0
[   14.150433] microcode: CPU10 sig=0x206d7, pf=0x4, revision=0x0
[   14.151131] microcode: CPU11 sig=0x206d7, pf=0x4, revision=0x0
[   14.151891] microcode: Microcode Update Driver: v2.00 tigran@aivazian.fsnet.co.uk, Peter Oruba
[   14.156187] kvm: disabled by bios
[   14.174906] input: HDA Intel PCH Line as /devices/pci0000:00/0000:00:1b.0/sound/card0/input7
[   14.174980] input: HDA Intel PCH Front Mic as /devices/pci0000:00/0000:00:1b.0/sound/card0/input8
[   14.175025] input: HDA Intel PCH Rear Mic as /devices/pci0000:00/0000:00:1b.0/sound/card0/input9
[   14.175062] input: HDA Intel PCH Front Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card0/input10
[   14.175099] input: HDA Intel PCH Line Out Side as /devices/pci0000:00/0000:00:1b.0/sound/card0/input11
[   14.175133] input: HDA Intel PCH Line Out CLFE as /devices/pci0000:00/0000:00:1b.0/sound/card0/input12
[   14.175170] input: HDA Intel PCH Line Out Surround as /devices/pci0000:00/0000:00:1b.0/sound/card0/input13
[   14.175206] input: HDA Intel PCH Line Out Front as /devices/pci0000:00/0000:00:1b.0/sound/card0/input14
[   14.175408] hda_intel: Disabling MSI
[   14.175418] hda-intel: 0000:02:00.1: Handle VGA-switcheroo audio client
[   14.189118] mei 0000:00:16.0: setting latency timer to 64
[   14.189176] mei 0000:00:16.0: irq 84 for MSI/MSI-X
[   14.193411] mei 0000:00:16.0: wd: failed to find the client
[   14.219016] kvm: disabled by bios
[   14.289069] usb 3-2: reset high-speed USB device number 2 using xhci_hcd
[   14.319388] xhci_hcd 0000:06:00.0: xHCI xhci_drop_endpoint called with disabled ep ffff88021fa2f240
[   14.319390] xhci_hcd 0000:06:00.0: xHCI xhci_drop_endpoint called with disabled ep ffff88021fa2f200
[   14.319392] xhci_hcd 0000:06:00.0: xHCI xhci_drop_endpoint called with disabled ep ffff88021fa2f280
[   14.319393] xhci_hcd 0000:06:00.0: xHCI xhci_drop_endpoint called with disabled ep ffff88021fa2f2c0
[   14.319394] xhci_hcd 0000:06:00.0: xHCI xhci_drop_endpoint called with disabled ep ffff88021fa2f300
[   14.319395] xhci_hcd 0000:06:00.0: xHCI xhci_drop_endpoint called with disabled ep ffff88021fa2f340
[   14.319396] xhci_hcd 0000:06:00.0: xHCI xhci_drop_endpoint called with disabled ep ffff88021fa2f380
[   14.319863] kvm: disabled by bios
[   14.321709] kvm: disabled by bios
[   14.324988] kvm: disabled by bios
[   14.326729] cfg80211: Updating information on frequency 2412 MHz for a 20 MHz width channel with regulatory rule:
[   14.326733] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326746] cfg80211: Updating information on frequency 2417 MHz for a 20 MHz width channel with regulatory rule:
[   14.326747] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326748] cfg80211: Updating information on frequency 2422 MHz for a 20 MHz width channel with regulatory rule:
[   14.326749] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326750] cfg80211: Updating information on frequency 2427 MHz for a 20 MHz width channel with regulatory rule:
[   14.326751] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326752] cfg80211: Updating information on frequency 2432 MHz for a 20 MHz width channel with regulatory rule:
[   14.326753] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326754] cfg80211: Updating information on frequency 2437 MHz for a 20 MHz width channel with regulatory rule:
[   14.326755] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326756] cfg80211: Updating information on frequency 2442 MHz for a 20 MHz width channel with regulatory rule:
[   14.326757] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326757] cfg80211: Updating information on frequency 2447 MHz for a 20 MHz width channel with regulatory rule:
[   14.326758] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326759] cfg80211: Updating information on frequency 2452 MHz for a 20 MHz width channel with regulatory rule:
[   14.326760] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326761] cfg80211: Updating information on frequency 2457 MHz for a 20 MHz width channel with regulatory rule:
[   14.326762] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326763] cfg80211: Updating information on frequency 2462 MHz for a 20 MHz width channel with regulatory rule:
[   14.326764] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
[   14.326765] cfg80211: Updating information on frequency 2467 MHz for a 20 MHz width channel with regulatory rule:
[   14.326766] cfg80211: 2457000 KHz - 2482000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[   14.326766] cfg80211: Updating information on frequency 2472 MHz for a 20 MHz width channel with regulatory rule:
[   14.326767] cfg80211: 2457000 KHz - 2482000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[   14.326768] cfg80211: Updating information on frequency 2484 MHz for a 20 MHz width channel with regulatory rule:
[   14.326769] cfg80211: 2474000 KHz - 2494000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
[   14.328616] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   14.328776] Registered led device: rt2800usb-phy0::radio
[   14.328786] Registered led device: rt2800usb-phy0::assoc
[   14.328796] Registered led device: rt2800usb-phy0::quality
[   14.328829] usbcore: registered new interface driver rt2800usb
[   14.421000] kvm: disabled by bios
[   14.445007] kvm: disabled by bios
[   14.469140] kvm: disabled by bios
[   14.521429] kvm: disabled by bios
[   14.544950] kvm: disabled by bios
[   15.060182] input: HDA NVidia HDMI/DP,pcm=9 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input15
[   15.060359] input: HDA NVidia HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input16
[   15.060476] input: HDA NVidia HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input17
[   15.060591] input: HDA NVidia HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:02.0/0000:02:00.1/sound/card1/input18
[   15.819974] EXT4-fs (sda2): re-mounted. Opts: errors=remount-ro
[   15.846136] init: failsafe main process (1157) killed by TERM signal
[   15.926810] Bluetooth: Core ver 2.16
[   15.926824] NET: Registered protocol family 31
[   15.926825] Bluetooth: HCI device and connection manager initialized
[   15.926826] Bluetooth: HCI socket layer initialized
[   15.926826] Bluetooth: L2CAP socket layer initialized
[   15.926829] Bluetooth: SCO socket layer initialized
[   15.928292] Bluetooth: RFCOMM TTY layer initialized
[   15.928296] Bluetooth: RFCOMM socket layer initialized
[   15.928297] Bluetooth: RFCOMM ver 1.11
[   15.929189] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   15.929191] Bluetooth: BNEP filters: protocol multicast
[   15.954655] ppdev: user-space parallel port driver
[   15.960394] type=1400 audit(1398328277.842:8): apparmor="STATUS" operation="profile_load" name="/usr/lib/cups/backend/cups-pdf" pid=1239 comm="apparmor_parser"
[   15.960638] type=1400 audit(1398328277.842:9): apparmor="STATUS" operation="profile_load" name="/usr/sbin/cupsd" pid=1239 comm="apparmor_parser"
[   15.992245] type=1400 audit(1398328277.874:10): apparmor="STATUS" operation="profile_replace" name="/sbin/dhclient" pid=1275 comm="apparmor_parser"
[   15.992368] type=1400 audit(1398328277.874:11): apparmor="STATUS" operation="profile_load" name="/usr/sbin/tcpdump" pid=1281 comm="apparmor_parser"
[   16.179871] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   16.180496] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   16.181836] tg3 0000:08:00.0: irq 85 for MSI/MSI-X
[   16.181841] tg3 0000:08:00.0: irq 86 for MSI/MSI-X
[   16.181856] tg3 0000:08:00.0: irq 87 for MSI/MSI-X
[   16.181859] tg3 0000:08:00.0: irq 88 for MSI/MSI-X
[   16.181863] tg3 0000:08:00.0: irq 89 for MSI/MSI-X
[   16.635537] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   16.635707] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
sam@sam:/media/ebee5541-bbe5-42c2-91d6-664e1bb90c75/var/log$

**Comment by jonbinney** [comment]
This kind of problem is probably better suited to answers.ros.org . Is issue can probably be closed - if you can narrow it down to a problem in gazebo_ros_pkgs, then you can open a more detailed issue here.
