### ISSUE TITLE
gazebo_ros_imu accelerations

### ISSUE THREAD

**Issue by progtologist** [ros-simulation/gazebo_ros_pkgs#195]
In the current implementation, the accelerations reported by the IMU are calculated by differentiating the velocity of the link.

This approach is error prone, differentiating sensor measurements is almost always a bad idea, since you are mostly getting the differentiation of the sensor noise. Also, in cases were the link is static, the measured acceleration appears to be zero, meaning gravity is not taken into account.

Gazebo provides methods for getting the accelerations of a link and this has been implemented in hector_gazebo_plugins correctly here:
https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/blob/hydro-devel/hector_gazebo_plugins/src/gazebo_ros_imu.cpp in line 225.

A similar approach must be used to make gazebo_ros_imu plugin functional.

**Comment by jonbinney** [comment]
Sounds useful! Want to implement this and create a pull request? :-)

**Comment by progtologist** [comment]
Ok, I will fork it and make a pull request after testing it!

**Comment by jonbinney** [comment]
If you can implement it so that switching the new and old methods of computing accelerations are switchable using a parameter, that would be best. Then if there are any cases where the old method works better, people will have the ability to fall back to it.

**Comment by progtologist** [comment]
After trying to implement it, I found out that gazebo acceleration getters are not functioning properly so until this is fixed for gazebo I am guessing we are stuck with differentiating the velocities.
More information can be found [here](https://bitbucket.org/osrf/gazebo/issue/243/getlinearacceleration-always-returns-zeros)

**Comment by jonbinney** [comment]
@progtologist thanks for looking into this. I'll keep an eye on that gazebo issue.
