### ISSUE TITLE
gazebo_ros: Getting remote endpoint failed terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'

### ISSUE THREAD

**Issue by ghost** [ros-simulation/gazebo_ros_pkgs#196]
Hi.

I am running Ubuntu 14.04 and have installed ROS Indigo from the debs. Everything is installed from scratch. Nothing except the `ros-desktop` package has been installed.

I want to start Gazebo from ROS as described on the tutorial, using:

```
$ roslaunch gazebo_ros empty_world.launch
```

That fails due to the following error:

```
Getting remote endpoint failed
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  remote_endpoint: Transport endpoint
```

Not sure if this is the root cause, the full log is bellow. There are strange warnings in the previous log entries.

Not sure if it is related to ROS or Gazebo either. Gazebo looks fine, I can start it without issue.

It is related to boost and therefore not linked to `roslaunch`, cf this [issue](https://github.com/ros/ros_comm/issues/421).

I have posted a question on the ROS forum:

http://answers.ros.org/question/168856/fails-gazebo-to-start-from-ros-boostexception_detail-error/

This question on the Gazebo forum describes the same issue:

http://answers.gazebosim.org/question/6271/getting-remote-endpoint-failed-let-gazebo-gui/

```
$ roslaunch gazebo_ros empty_world.launch
... logging to /home/arnaud/.ros/log/251a3d96-e35b-11e3-9539-0016eae586be/roslaunch-hercules-11967.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://hercules:46195/

SUMMARY
========

PARAMETERS
 * /rosdistro: <...>
 * /rosversion: <...>
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)

auto-starting new master
process[master]: started with pid [11979]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 251a3d96-e35b-11e3-9539-0016eae586be
process[rosout-1]: started with pid [11992]
started core service [/rosout]
process[gazebo-2]: started with pid [12016]
/opt/ros/indigo/lib/gazebo_ros/gzserver: 5: [: Linux: unexpected operator
process[gazebo_gui-3]: started with pid [12020]
/opt/ros/indigo/lib/gazebo_ros/gzclient: 5: [: Linux: unexpected operator
Gazebo multi-robot simulator, version 2.2.2
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 2.2.2
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Msg Waiting for masterError [Connection.cc:787] Getting remote endpoint failed
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  remote_endpoint: Transport endpoint is not connected
[ INFO] [1400946636.551182005]: Finished loading Gazebo ROS API Plugin.
Msg Waiting for master
[ INFO] [1400946636.557603492]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.1.211
Aborted (core dumped)
[gazebo_gui-3] process has died [pid 12020, exit code 134, cmd /opt/ros/indigo/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/arnaud/.ros/log/251a3d96-e35b-11e3-9539-0016eae586be/gazebo_gui-3.log].
log file: /home/arnaud/.ros/log/251a3d96-e35b-11e3-9539-0016eae586be/gazebo_gui-3*.log
[ INFO] [1400946637.091142150, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1400946637.167613885, 0.093000000]: Physics dynamic reconfigure ready.
^C[gazebo-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by ghost** [comment]
Could help, when starting Gazebo step by step (`roscore`, `rosrun gazebo_ros gzserver`, `rosrun gazebo_ros gzclient`), that works. But `roscore` and `rosrun gazebo_ros gazebo` fail to start it properly and trigger the same messages.

**EDIT:** `rosrun gazebo_ros gazebo` is fine (most of the time). `roslaunch gazebo_ros empty_world.launch` is still bugged.

**Comment by jonbinney** [comment]
I think this message is what gzclient outputs when gzserver dies unexpectedly. I see that you're using gazebo 2.2.2, so i suspect you're using ROS indigo on ubuntu 14.04. I get the same error because the server dies due to this segfault in the sdformat library: https://bitbucket.org/osrf/sdformat/issue/63/gzsdf-segfaults-in-trusty#comment-10466948

**Comment by ghost** [comment]
Correct, Ubuntu 14.04 + ROS Indigo (I have updated the initial post with the ROS version). Thanks for the issue, I will monitor it.

**Comment by scpeters** [comment]
Thanks for the report, we are looking into it. I also noticed that error message in a [jenkins test failure on trusty](http://build.osrfoundation.org/job/gazebo-default-devel-trusty-amd64/25/testReport/junit/%28root%29/UNIT_gz_TEST/test_ran/):

```
241: [ RUN      ] gzTest.Joint
241: [1;32m[Msg] [0m[1;32mWaiting for master.[0m[1;32m
241: [1;31m[Err] [0m[1;31m[[0m[1;31mConnection.cc[0m[1;31m:[0m[1;31m787[0m[1;31m] [0m[1;31mGetting remote endpoint failed[0m[1;31m
241: [0m[1;31m[0mterminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
241:   what():  remote_endpoint: Transport endpoint is not connected
241: [0m[1;32m[0m
117/118 Test #241: UNIT_gz_TEST ...........................***Exception: Other 61.19 sec
```

I'll try to reproduce that as well, since I think it is separate from the gzsdf / urdf error.

**Comment by jonbinney** [comment]
ok, i'm getting this now too, even when compiling gazebo from source.

**Comment by ghost** [comment]
I need to correct what I said.

This one works after a fresh reboot:

```
$ roslaunch gazebo_ros empty_world.launch
```

When I tried to spawn a robot, the bug is triggered. When I try to start the empty world after, that fails too. So it was quite tricky to isolate the bug.

**Comment by jonbinney** [comment]
I've noticed that i get this error more often when i launch for the first time after a clean reboot.

**Comment by hsu** [comment]
referencing [root issue](https://bitbucket.org/osrf/gazebo/issue/1204/trusty-remote_endpoint-transport-endpoint), as pointed out to me by @scpeters, running `gzclient` before starting a server on trusty triggers this error.

**Comment by j-rivero** [comment]
Seems to me that this was caused by a bug in upstream boost 1.54 fixed long ago. For details, please check @hsu comment just above.
