### ISSUE TITLE
Adding robot_namespace to sdf nested models

### ISSUE THREAD

**Issue by fmder** [ros-simulation/gazebo_ros_pkgs#2]
Currently when adding a gazebo sdf robot, nothing is done with the `-robot_namespace` argument.

Adding

```
this->walkChildAddRobotNamespace(&gazebo_model_xml);
```

at the end of the `else if (IsSDF(model_xml))` (approximately line 537 of file gazebo_ros_api_plugin.cpp) adds the feature for the first level of the robot model, but the nested 

```
<include>
  <uri>model://mymodel</uri>
</include>
```

are unafected as the model is not flattened. I see several solutions
1. Flatten manually every model when using spawn model.
2. Have the flattening done in the ros_api C part.
3. Have a python script doing the flattening.

This issue is mostly to know the status (as I'm sure this is known) of the feature and to inquiry any other detail I missed before trying to work on that.

**Comment by davetcoleman** [comment]
Fixing this would be much appreciated, though John commented that it might be easier to add this functionality inside of Gazebo's URDF parsing functionality in the Gazebo repo at `gazebo/sdf/interface/parser_urdf.cc`

A python script sounds like a dirty solution. Flattening within Gazebo would be cleanest.

**Comment by davetcoleman** [comment]
Did you find a fix for this issue?

**Comment by fmder** [comment]
Unfortunately, I don't think there is an _easy_ solution for nested sdf model, since it would require access to the model database in the ros api plugin. Like you mentioned, the best option is probably an integrated solution in gazebo directly.

For now, I use a URDF/XACRO model, which work well once the walkChildAddRobotNamespace function is reactivated. I have a multi turtlebot kobuki/kinect/hokuyo running.

**Comment by davetcoleman** [comment]
I've filed an issue with Gazebo [here](https://bitbucket.org/osrf/gazebo/issue/734/adding-robot_namespace-to-sdf-nested)
