### ISSUE TITLE
Gazebo gui gets loaded automatically when running gazebo script.

### ISSUE THREAD

**Issue by piyushk** [ros-simulation/gazebo_ros_pkgs#20]
The GUI gets loaded by default when you run the gazebo script. This behavior is different from simulator-gazebo. Is this intended?

**Comment by davetcoleman** [comment]
Yes, we tried to re-align the scripts to match what the stand-alone Gazebo does. The commands correspond now as so:

**Run Just Server**
gzserver
rosrun gazebo_ros gzserver

**Run Just GUI**
gzclient
rosrun gazebo_ros gzclient

**Run Both**
gazebo
rosrun gazebo_ros gazebo

**Comment by davetcoleman** [comment]
This was documented in the section [Running Gazebo](http://gazebosim.org/wiki/Tutorials/1.9/Overview_of_new_ROS_integration#Running_Gazebo) and I just updated it to clarify it even more.

**Comment by piyushk** [comment]
Thanks for pointing me to the documentation. It answers my question. I will close this issue thread.
