### ISSUE TITLE
wrong repository url in package.xml files

### ISSUE THREAD

**Issue by dirk-thomas** [ros-simulation/gazebo_ros_pkgs#200]
affects all packages and branches

**Comment by jonbinney** [comment]
Just made PR's to fix this in the groovy-devel, hydro-devel, and indigo-devel branches. There will also need to be releases for all three branches, right?

**Comment by dirk-thomas** [comment]
Not necessarily. The documentation used for the wiki is the most important one and that is generated from the branches.

**Comment by davetcoleman** [comment]
I believe this can be closed now? Please re-open if not.
