### ISSUE TITLE
Release ros-indigo-gazebo-ros-control

### ISSUE THREAD

**Issue by davetcoleman** [ros-simulation/gazebo_ros_pkgs#206]
gazebo_ros_control is failing in the [build farm](http://jenkins.ros.org/job/ros-indigo-gazebo-ros-control_binarydeb_trusty_amd64/37/console) but the fix is already out [here](https://github.com/ros-simulation/gazebo_ros_pkgs/commit/b9d24d52d835781186ed010791179aa955014747) it just needs to be released. I will happily do it but want to double check with the other Gazebo maintainers @scpeters

**Comment by scpeters** [comment]
Go for it; thanks!

**Comment by davetcoleman** [comment]
Also, are we ready to change the default branch of this repo to `indigo-devel`?

**Comment by adolfo-rt** [comment]
If the release incorporates the changes proposed in #208, then `control_toolbox` needs to be released first, otherwise the buildfarm is going to complain.

**Comment by davetcoleman** [comment]
Good point.

**Comment by adolfo-rt** [comment]
control_toolbox 1.12.1 for indigo: https://github.com/ros/rosdistro/pull/4676

**Comment by abubeck** [comment]
Release is not in shadow-fixed yet. #217 should fix the cmake issue.

**Comment by adolfo-rt** [comment]
I just verified that prerelease tests are passing for the dev version of `gazebo_ros_pkgs`. Since I can't release `gazebo_ros_control` in isolation, I'd like to get confirmation from `gazebo_ros` and `gazebo_plugins` maintainers that we're OK to do a **patch** release into indigo (2.4.3 → 2.4.4).

Please shout if unreleased changesets are not ready to be merged, or if they warrant a minor (not patch) version bump.

**Comment by adolfo-rt** [comment]
The maintainers of  `gazebo_ros` and `gazebo_plugins` are @hsu and @davetcoleman. Could you please give your OK for a patch release? (see above comment).

Also, I don't have privileges to release packages in this repo, so @davetcoleman, could you do it when all lights are green?.

**Comment by scpeters** [comment]
@hsu is on vacation this week. I'll check on it for you.

**Comment by scpeters** [comment]
Everything looks in order. I have permissions to release, so I will do so.

**Comment by scpeters** [comment]
https://github.com/ros/rosdistro/pull/5042

**Comment by davetcoleman** [comment]
Thanks!

**Comment by scpeters** [comment]
Packages are built successfully.

**Comment by adolfo-rt** [comment]
Cool, thanks @scpeters!
