### ISSUE TITLE
itnode_->advertise called with wrong "latched" argument

### ISSUE THREAD

**Issue by dpinol** [ros-simulation/gazebo_ros_pkgs#212]
GazeboRosCameraUtils::LoadThread makes this call. Last argument should be the latched boolean, and instead a CallbackQueue is passed

```
  this->image_pub_ = this->itnode_->advertise(
    this->image_topic_name_, 2,
    boost::bind(&GazeboRosCameraUtils::ImageConnect, this),
    boost::bind(&GazeboRosCameraUtils::ImageDisconnect, this),
    ros::VoidPtr(), &this->camera_queue_);
```

This is easily spotted compiling with clang:

```
/home/dani/svn/catkin_ws-clang3.5-analyzer/src/gazebo_ros_pkgs/gazebo_plugins/src/gazebo_ros_camera_utils.cpp:307:28: error: 
      address of 'this->camera_queue_' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
    ros::VoidPtr(), &this->camera_queue_);
                     ~~~~~~^~~~~~~~~~~~~
```

**Comment by jonbinney** [comment]
Interesting - so it is also not actually using the queue, right?

**Comment by dpinol** [comment]
I don't have the code in front of me, but I think that for that you have to associate the queue to the node.

**Comment by j-rivero** [comment]
Looking into the API, I would say there is in fact a bug.

What I think that is happening is: the reference to a class member is passed and evaluated as a boolean. Since the reference is not null, the evaluation results into true.

**Comment by scpeters** [comment]
code in [gazebo_plugins/src/gazebo_ros_camera_utils.cpp:319-323](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/c190bf69aa5994351114430c529c5c1dd892b8dc/gazebo_plugins/src/gazebo_ros_camera_utils.cpp#L319-L323)

**Comment by scpeters** [comment]
Hm...the online docs don't show a bool in the API:
- http://docs.ros.org/indigo/api/roscpp/html/structros_1_1AdvertiseOptions.html

**Comment by scpeters** [comment]
https://github.com/ros/ros_comm/blob/indigo-devel/clients/roscpp/include/ros/advertise_options.h#L134-L159

**Comment by j-rivero** [comment]
fixed.
