### ISSUE TITLE
How to use Gazebo-plugin?

### ISSUE THREAD

**Issue by fanxiad** [ros-simulation/gazebo_ros_pkgs#216]
"export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:~/OD_gazebo_plugin/build"

run gazebo ,it has error failed to load plugin...

**Comment by scpeters** [comment]
Can you give a little more context? Are you working from a tutorial? Can you paste the actual console output? Thanks.

**Comment by bit-pirate** [comment]
Probably can close this one, since she/he didn't reply.
