### ISSUE TITLE
Tutorials - URDF Example with Baxter

### ISSUE THREAD

**Issue by hboortz** [ros-simulation/gazebo_ros_pkgs#22]
"rosrun gazebo_ros spawn_model -file `rospack find baxter_description`/urdf/baxter.urdf -urdf -z 1 -model baxter"
is not working for me. It's hanging after this: 
rosrun gazebo_ros spawn_model -file `rospack find baxter_description`/urdf/baxter.urdf -urdf -z 1 -model baxter
[INFO] [WallTime: 1371588399.946251] [0.000000] Loading model xml from file
[INFO] [WallTime: 1371588399.946837] [0.000000] waiting for service /gazebo/spawn_urdf_model

**Comment by davetcoleman** [comment]
This was a ROS workspace setup issue, fixed in person.
