### ISSUE TITLE
Release a new version of ros_gazebo_pkgs for hydro/indigo

### ISSUE THREAD

**Issue by j-rivero** [ros-simulation/gazebo_ros_pkgs#226]
I'm going to release a new version of ros_gazebo_pkgs for both Hydro and Indigo. @adolfo-rt, @hsu, @scpeters FYI.

**Comment by adolfo-rt** [comment]
> I'm going to release a new version of ros_gazebo_pkgs for both Hydro and
> Indigo. @adolfo-rt, @hsu, @scpeters FYI.

Great, thanks!

**Comment by j-rivero** [comment]
Both hydro/indigo versions were generated and the PRs merged into rosdistro.
