### ISSUE TITLE
 Release a new version of ros_gazebo_pkgs for hydro/indigo (2.4.6)

### ISSUE THREAD

**Issue by j-rivero** [ros-simulation/gazebo_ros_pkgs#236]
Ongoing.

**Comment by j-rivero** [comment]
Done for both.

**Comment by j-rivero** [comment]
Looks like the jobs failed. There is a `socket timeout` message in log but i don't understand the cause of the error, any idea? + @tfoote 
- http://jenkins.ros.org/job/devel-hydro-gazebo_ros_pkgs/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/22/changes
- http://jenkins.ros.org/job/devel-indigo-gazebo_ros_pkgs/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/15/changes

**Comment by tfoote** [comment]
It's all good. I retriggered it and it passed. Timeouts like that are often network glitches downloading resources.
