### ISSUE TITLE
image_connect_count_ never initialized

### ISSUE THREAD

**Issue by fmder** [ros-simulation/gazebo_ros_pkgs#248]
I get a segmentation fault in gazebo_ros_depth_camera using ros groovy and gazebo 1.9.2. The variable image_connect_count_ is never initialized (as many other shared pointers). The constructor of GazeboRosCameraUtils should be 

```
GazeboRosCameraUtils::GazeboRosCameraUtils() : image_connect_count_(new int(0))
```

This solves my segmentation fault for image_connect_count_ in GazeboRosDepthCamera::PointCloudConnect() operator*()

**Comment by kev-the-dev** [comment]
Fixed in #748.
