### ISSUE TITLE
[gazebo_ros_control] Adding E-stop support to gazebo_ros_control

### ISSUE THREAD

**Issue by jim-rothrock** [ros-simulation/gazebo_ros_pkgs#258]
I am adding E-stop support to gazebo_ros_control. This will allow emergency stop functionality to be tested in a simulated environment. The E-stop system is implemented as described in the ROSCon 2014 ros_control presentation. Before submitting a pull request, I'll describe the E-stop modifications here, to give people a chance to bring up any issues.
- gazebo_ros_control subscribes to the topic specified by the new SDF parameter eStopTopic, which has the default value "activate_e_stop". The topic is of type std_msgs/Bool, and exists in the namespace specified by the robotNamespace parameter.
- When gazebo_ros_control receives a "true" message from activate_e_stop, the simulated actuators are commanded to stop by passing ros::Time(0) as the first argument to robot_hw_sim_->writeSim(). Ideally, a new parameter would be added to writeSim(), but I don't want to break ABI compatibility with existing gazebo_ros_control plugins. If anyone has a better idea, let me know.
- When the receipt of a "false" message from activate_e_stop causes the E-stop to be released, "true" is passed as the third argument to controller_manager_->update() for one control cycle, and sim_time_ros is passed to robot_hw_sim_->writeSim().
- In DefaultRobotHWSim::writeSim(), when the "time" parameter is less than or equal to zero, the following take place:
  - For "position" joints, the current position is maintained.
  - For "velocity" joints, the velocity is set to zero.
  - For "effort" joints, the effort is set to zero.

Where should gazebo_ros_control's documentation (e.g. a description of the eStopTopic parameter) exist? I would expect it to be in http://wiki.ros.org/gazebo_ros_control, but there's nothing there. The README.md in the repository points to http://gazebosim.org/tutorials?cat=connect_ros, from which one can find the ros_control section. Is this the recommended location for gazebo_ros_control documentation?

**Comment by adolfo-rt** [comment]
Hey @jim-rothrock, great initiative. I see a lot of value in having a reference implementation of e-stop handling.

Does your proposal only affect the `DefaultRobotHWSim` implementation?. I get the impression that it does, and I would agree with this course of action, and to not impose one E-stop implementation in the general case. This would mean that the `eStopTopic` SDF element would only be read by `DefaultRobotHWSim` implementation, and not by `RobotHWSim`, correct?.

I'm not very fond of using zero time as an indicator of the e-stop state. Could you not just use a new private member for storing the last state read by the topic?. This would preserve the API and not introduce confusing semantics.

The policy when the e-stop is active is a bit tricky, and I don't think there is any one-size-fits-all solution. Some robots hold position, others gradually reach a minimal potential energy configuration, yet others might do something else. Apart from your suggestion, I can think of no other simple solution, and I don't know how well this will work for others.

Finally, on documentation. I would vote in favor of having the basic description of the package on the ROS wiki, which as you saw, doesn't exist yet.

**Comment by jim-rothrock** [comment]
> Does your proposal only affect the DefaultRobotHWSim implementation?. I get the impression that it 
> does, and I would agree with this course of action, and to not impose one E-stop implementation in 
> the general case.

GazeboRosControlPlugin::Load() subscribes to the E-stop topic, and the the callback is GazeboRosControlPlugin::eStopCB(), which sets a flag in the object GazeboRosControlPlugin. I do the message handling in GazeboRosControlPlugin so that classes derived from RobotHWSim won't have to duplicate the code. In any case, GazeboRosControlPlugin::Update() needs to be informed about the E-stop by some mechanism, since it is responsible for resetting the controller manager when it calls controller_manager_->update().

> This would mean that the eStopTopic SDF element would only be read by 
> DefaultRobotHWSim implementation, and not by RobotHWSim, correct?.

The eStopTopic element is read in GazeboRosControlPlugin::Load(), because that is where the other Gazebo plugin parameters (e.g. robotNamespace, robotParam, robotSimType) are read. My philosophy is that the RobotHWSim plugins should only have to worry about which Gazebo calls to make in response to an E-stop, and should not have to be concerned with ROS message handling. If you want me to move as much of the E-stop code as possible into DefaultRobotHWSim, I can do that. It just seems like the ROS E-stop parameter reading and subscription code is something that should be shared by all RobotHWSim plugins, and therefore should be in GazeboRosControlPlugin.

> I'm not very fond of using zero time as an indicator of the e-stop state. Could you not just use a new 
> private member for storing the last state read by the topic?. This would preserve the API and not 
> introduce confusing semantics.

That's fine with me, as long as you are not concerned with breaking ABI compatibility with existing RobotHWSim plugins. They will have to be recompiled.

> The policy when the e-stop is active is a bit tricky, and I don't think there is any one-size-fits-all 
> solution. Some robots hold position, others gradually reach a minimal potential energy 
> configuration, yet others might do something else. Apart from your suggestion, I can think of no 
> other simple solution, and I don't know how well this will work for others.

Users who don't want the default behavior can create their own class derived from RobotHWSim.

**Comment by adolfo-rt** [comment]
Your observation about preserving ABI compatibility is relevant (packages have version > 1.0). Still, a quick look through the repo's history reveals that in fact ABI compatibility has been broken [more](https://github.com/ros-simulation/gazebo_ros_pkgs/commit/6f302ede1648c89d378307a6753f9007d697bad9) [than](https://github.com/ros-simulation/gazebo_ros_pkgs/commit/69f25cabf40c38ad8513614052f3a701b2d12eb8) [once](https://github.com/ros-simulation/gazebo_ros_pkgs/commit/9469e85ad817163f94be97d66cc45e6bec5dab28). This might be due to the nature of this repo, which is a mix of many somewhat disconnected parts, hence semantic versioning is not fully enforced. Any comment on this?, @j-rivero @scpeters.
If an ABI break would be acceptable, the new class member would be the cleanest solution.

---

On how to distribute the code between the `RobotHWSim` and `DefaultRobotHWSim` classes, my only concern is that we should not impose interfaces or policies that might not be appropriate for some users. In our particular case, setting effort joints immediately to zero upon E-stop activation would probably not be the best policy, but we don't use `DefaultRobotHWSim` anyway.

**Comment by j-rivero** [comment]
`gazebo_ros_pkg` is a ROS package and we usually follow ROS rules unless a good reason not to do it appears. AFAIK, there are no rules about not breaking the ABI in ROS packages right now. Every new change will trigger the recompilation of all packages depending on the one that is changing so you don't have to worry about breaking ABI. Semantic versioning does not apply here, indeed.

**Comment by adolfo-rt** [comment]
Thanks for the clarification @j-rivero . Adhering to semantic versioning is a good idea even if not required by the ROS rules, but I have to agree that on this repo it might be too restrictive, especially considering that `gazebo_ros_control` relates to the `ros_control` project, which is in pre-1.0 stage.

I also admit to have had a confusion in my mind wrt the ROS rules, which I just realized came from [REP-9](http://www.ros.org/reps/rep-0009.html), which has been **withdrawn**.

**Comment by jim-rothrock** [comment]
I have added E-stop support to gazebo_ros_control. Pull request: https://github.com/ros-simulation/gazebo_ros_pkgs/pull/265. I'll add documentation to http://wiki.ros.org/gazebo_ros_control once the PR is merged.
