### ISSUE TITLE
Failed to link with ogremain on OSX 10.10

### ISSUE THREAD

**Issue by rcodddow** [ros-simulation/gazebo_ros_pkgs#269]
'''
[ 75%] Linking CXX shared library /Users/robert/ros_catkin_ws/devel_isolated/gazebo_plugins/lib/libgazebo_ros_video.dylib
Built target gazebo_ros_diff_drive
[ 77%] Built target hokuyo_node
ld: library not found for -lOgreMain
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [/Users/robert/ros_catkin_ws/devel_isolated/gazebo_plugins/lib/libgazebo_ros_video.dylib] Error 1
make[1]: **\* [CMakeFiles/gazebo_ros_video.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 80%] Built target camera_synchronizer
[ 83%] Built target gazebo_ros_camera_utils
make: **\* [all] Error 2
'''

**Comment by jbohren** [comment]
Do you have the ogre SDK installed?

**Comment by rcodddow** [comment]
brew reveals that indeed ogre is installed

'''
dagobah:~ robert$ brew install ogre
==> Installing ogre from osrf/homebrew-simulation
Warning: ogre-1.7.4 already installed
'''

**Comment by jbohren** [comment]
Try adding `${OGRE_LIBRARY_DIRS}` below this line: https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_plugins/CMakeLists.txt#L72

**Comment by rcodddow** [comment]
that fixed it

**Comment by jbohren** [comment]
Haha, wait. Could you submit a PR with this patch?

**Comment by rcodddow** [comment]
sure

**Comment by jbohren** [comment]
Fixed in #270 and #271
