### ISSUE TITLE
f3d no force data

### ISSUE THREAD

**Issue by zchen24** [ros-simulation/gazebo_ros_pkgs#281]
The f3d plugin only reports wrench data, but force data is always 0. 
I am using Gazebo with ODE physics engine. 
This might be a Gazebo issue.

**Comment by kev-the-dev** [comment]
[The code](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_plugins/src/gazebo_ros_f3d.cpp#L175) certainly looks like the ROS plugin does it's job here. Are you sure there is actually a force being applied? Please also leave version info about your issue (ROS Version, gazebo version).

**Comment by zchen24** [comment]
@ironmig Thanks for replying. Given it was 4 years ago, I can no longer recall these details. I will close this issue.
