### ISSUE TITLE
Fix 2.4.7 Indigo release (the debian metadata about gazebo is wrong)

### ISSUE THREAD

**Issue by j-rivero** [ros-simulation/gazebo_ros_pkgs#285]
rosdep was incorrect in my local system and the gazebo upstream package was resolve to gazebo4 instead of the usual gazebo2 for Indigo. Sorry about that. I'm releasing a new version to fix this problem.

Thanks to Florian Weißhardt for spotting the problem.

**Comment by j-rivero** [comment]
2.4.7-1 https://github.com/ros/rosdistro/pull/6587

**Comment by j-rivero** [comment]
Done.

**Comment by scpeters** [comment]
~~Is this related to https://bitbucket.org/osrf/gazebo/issue/1393/after-apt-get-update-cannot-run-gazebo-or ?~~

EDIT: nevermind, I don't think so, that is related to drcsim and the user is building from source

**Comment by j-rivero** [comment]
Agree.
