### ISSUE TITLE
New releases: indigo 2.4.8 and hydro 2.3.8

### ISSUE THREAD

**Issue by j-rivero** [ros-simulation/gazebo_ros_pkgs#305]
I'm working on releasing new versions from indigo-devel and hydro-devel. I will post updates on this issue.

/cc @hsu @adolfo-rt @mikeferguson @scpeters

**Comment by hsu** [comment]
Thank you @j-rivero

**Comment by j-rivero** [comment]
Pull requests ready to be merged in rosdistro:
- Indigo: https://github.com/ros/rosdistro/pull/7552
- Hydro: https://github.com/ros/rosdistro/pull/7553

**Comment by j-rivero** [comment]
Both PRs has been merged. We are all set. Let me know here if you find any problem.
