### ISSUE TITLE
diff drive plugin has left and right backward

### ISSUE THREAD

**Issue by gerkey** [ros-simulation/gazebo_ros_pkgs#317]
I'm pretty sure that the diff drive plugin is getting the desired left and right wheel velocities backward when converting from vr and va.  [Here's](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_plugins/src/gazebo_ros_diff_drive.cpp#L265) the code:

```
wheel_speed_[LEFT] = vr + va * wheel_separation_ / 2.0;
wheel_speed_[RIGHT] = vr - va * wheel_separation_ / 2.0;
```

A positive va should induce counter-clockwise rotation, which requires the right wheel velocity to be larger than the left wheel velocity.  With the above code, we'll get the opposite.

Anecdotal support for this being a bug is provided by the [Gazebo tutorial example](http://gazebosim.org/tutorials?tut=ros_gzplugins&cat=connect_ros#DifferentialDrive), in which the left and right joints are swapped, presumably in an effort to work around the problem.

**Comment by maxbader** [comment]
Hello Gerkey

Have a look at the pull request #272 this plug-in has multiple enhancements and the joints are defined as supposed. 
Have a look on the multi_robot_scenario which can be launched out of the box.
 [gazebo_ros_pkgs/gazebo_plugins/test/multi_robot_scenario/xacro/p3dx/pioneer3dx_plugins.xacro](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_plugins/test/multi_robot_scenario/xacro/p3dx/pioneer3dx_plugins.xacro)

Greetings
Markus
