### ISSUE TITLE
gazebo_ros has undeclared run dependency on libgazebo5-dev

### ISSUE THREAD

**Issue by scpeters** [ros-simulation/gazebo_ros_pkgs#323]
The jade version of `gazebo_ros` declares a [build dependency on libgazebo5-dev](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_ros/package.xml#L27) and a [run dependency on gazebo5](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_ros/package.xml#L40).

However, the [gazebo_ros/scripts](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/jade-devel/gazebo_ros/scripts) are [using pkg-config](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_ros/scripts/gzserver#L21) to find the prefix for the gazebo setup.sh file. This implies a run dependency on the gazebo.pc file in `libgazebo5-dev`.

If you don't have `libgazebo5-dev` installed, this will cause simple roslaunch's of gazebo to fail with something like the following error message:

```
$ roslaunch gazebo_ros empty_world.launch
...
/opt/ros/jade/lib/gazebo_ros/gzclient: 17: .: Can't open /share/gazebo//setup.sh
/opt/ros/jade/lib/gazebo_ros/gzserver: 22: .: Can't open /share/gazebo//setup.sh
[gazebo-2] process has died [pid 15709, exit code 2, cmd /opt/ros/jade/lib/gazebo_ros/gzserver -e ode worlds/empty.world __name:=gazebo __log:=~/.ros/log/bb3dc582-f051-11e4-96c1-902b3456ea33/gazebo-2.log].
log file: ~/.ros/log/bb3dc582-f051-11e4-96c1-902b3456ea33/gazebo-2*.log
[gazebo_gui-3] process has died [pid 15719, exit code 2, cmd /opt/ros/jade/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=~/.ros/log/bb3dc582-f051-11e4-96c1-902b3456ea33/gazebo_gui-3.log].
log file: ~/.ros/log/bb3dc582-f051-11e4-96c1-902b3456ea33/gazebo_gui-3*.log
```

Installing `libgazebo5-dev` is currently a valid workaround.

@wjwwood

**Comment by cmaestre** [comment]
Hello! While trying to install `libgazebo5-dev` I got an unmet dependency with `libogre-1.9-dev`:

```
The following packages have unmet dependencies.
 libgazebo5-dev : Depends: libogre-1.9-dev but it is not going to be installed
```

If I try to install it (`sudo apt-get install libogre-1.9-dev`) I get the following information:

```
The following packages will be REMOVED
  libogre-1.8-dev ros-jade-desktop
  ros-jade-desktop-full ros-jade-librviz-tutorial ros-jade-rqt-robot-plugins
  ros-jade-rqt-rviz ros-jade-rviz ros-jade-rviz-plugin-tutorials
  ros-jade-rviz-python-tutorial ros-jade-simulators ros-jade-urdf-tutorial
  ros-jade-visualization-tutorials ros-jade-viz
```

It looks like `libogre-1.9-dev` is not compatible with other features of Jade.

**Comment by scpeters** [comment]
Thanks for the report. Which Ubuntu distro are you using?

**Comment by cmaestre** [comment]
I am using Ubuntu 14.04.1 LTS

**Comment by scpeters** [comment]
We had intended to link against libogre-1.8-dev on trusty, as [discussed here](https://github.com/ros-infrastructure/rep/pull/89#issuecomment-69232117), but the gazebo deb is incorrectly linking with version 1.9 as you noted. We are [working on building new gazebo debs](https://bitbucket.org/osrf/release-tools/pull-request/88/fix-trusty-dependencies-for-vivid-gazebo/diff).

**Comment by cmaestre** [comment]
Hi! Are the new gazebo debs availables? Because it looks like this should be solved in builds 23 and 24, but when I try to install `libgazebo5-dev` I still get the same dependency. 

I am not sure of being using the good repo:

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

**Comment by scpeters** [comment]
@tfoote have you pulled the trusty debs from May 6?
- http://build.osrfoundation.org/job/gazebo5_vivid-debian-debbuilder/23/
- http://build.osrfoundation.org/job/gazebo5_vivid-debian-debbuilder/24

**Comment by tfoote** [comment]
I just tried importing them and they will not override the existing packages because they have the same filename. Can we get them with a debian increment on the build number?

**Comment by scpeters** [comment]
Ok, I bumped the arch number in the following builds:
- http://build.osrfoundation.org/job/gazebo5_vivid-debian-debbuilder/25/
- http://build.osrfoundation.org/job/gazebo5_vivid-debian-debbuilder/26/

**Comment by scpeters** [comment]
@cmaestre The new debs have been built, and it looks like they are already in the shadow-fixed repository. It should be working soon.

**Comment by cmaestre** [comment]
I just installed the library from the shadow-fixed repository and it works! Thanks a lot for the fast answer. You are doing great with ROS.

**Comment by Raym0ndKwan** [comment]
Works nice for me. Cheers.

**Comment by mechatron1991** [comment]
@scpeters I have similar issue. I am installing ros jade in debian jessie. I am using ros packages built for ubuntu vivid. I tried installing gazebo5 package via synaptic and this is the error that I got

gazebo5:
 Depends: libgazebo5 (=5.0.1-1~vivid) but it is not installable
 Depends: libsdformat2 but it is not going to be installed
 Depends: libspnav0 but it is not going to be installed
 Depends: gazebo5-common (=5.0.1-1~vivid) but it is not installable
 Recommends: gazebo5-plugin-base  but it is not installable

Any idea how to proceed ?

I am not aware if this is the right place to post it. Please correct me if I am wrong.

Thank you :)

**Comment by scpeters** [comment]
@mechatron1991 sorry I didn't respond to this comment sooner. Is it still an issue for you?

I see errors like this sometimes when I have another version of gazebo and/or sdformat installed. I usually try to remove all gazebo and sdformat debs then trying to reinstall the desired ones. Let me know if you have this issue.

**Comment by mechatron1991** [comment]
@scpeters Thank you for your reply. I still have this problem. The problem I have noticed so far is that gazebo package is not present in stable release(debian jessie) where as it is present in testing and unstable releases. I am working on installing gazebo from the source in debian jessie. Is it possible to make gazebo package available for debian jessie ?

**Comment by scpeters** [comment]
I'll need to ask @j-rivero for help with that question about debian jessie.

**Comment by mechatron1991** [comment]
@scpeters Thank you. Meanwhile, I had posted a question about installing gazebo from source in debian jessie in _gazebo answers_ website. I will update here if I find a solution to my problem.

**Comment by j-rivero** [comment]
> The problem I have noticed so far is that gazebo package is not present in stable release(debian jessie) where as it is present in testing and unstable releases.

That is right, the package was not old enough nor fully clean of bugs to go into stable on time for jessie.

There is an effort for migrating ROS packages to Debian which probably can help you to bring gazebo binaries to jessie. https://wiki.debian.org/DebianScience/Robotics/ROS
Check for the `http://sir.upc.edu/debian-robotics jessie-robotics main`which is managed by Leo Palomo-Avellaneda who works in debian-science and uses ROS.

**Comment by mechatron1991** [comment]
@j-rivero That solves the problem that I have. Thank you.

**Comment by jackieokay** [comment]
I noticed this issue in the package.xml; how will it affect the upgrade to Gazebo 7 in Xenial?

**Comment by scpeters** [comment]
I think the kinetic branch will need `libgazebo7-dev` as a run-time dependency in the package.xml
