### ISSUE TITLE
Ros MoveIt Planning Scene Plugin Compatibility in Indigo

### ISSUE THREAD

**Issue by nrontsis** [ros-simulation/gazebo_ros_pkgs#334]
I am not sure if this is the right place to ask.

@jbohren is the Ros MoveIt! Planning Scene Plugin [(this)](https://github.com/jhu-lcsr-forks/gazebo_ros_pkgs/blob/hydro-devel/gazebo_plugins/include/gazebo_plugins/gazebo_ros_moveit_planning_scene.h) compatible with Indigo?

MoveIt! is dying when I am trying it, and I am wondering if there is a compatibility issue.

Thanks,

Nikitas

**Comment by gavanderhoorn** [comment]
@nrontsis: please use the [appropriate tracker](https://github.com/ros-planning/moveit_ros/issues) for MoveIt related issues.

**Comment by mehditlili** [comment]
@gavanderhoorn I don't think that tracker is the correct place to post such an issue. The plugin itself is programmed on an old Gazebo version and since then the API has changed. So I think it makes sense to reopen this issue until that plugin (which mysteriously disappears starting from indigo) is fixed for new ros versions. The changes that need to be done do not seem very complicated and I'll see what I can do.

**Comment by gavanderhoorn** [comment]
@mehditlili: bit of a blast-from-the-past this.

**Comment by mehditlili** [comment]
@gavanderhoorn Yes but is there any new feature in Moveit/Gazebo that makes this plugin irrelevant? I was playing around with a robotic arm in gazebo but moveit kept planning paths that collide with objects that are spawned manually after loading the world. Those objects do also not appear in rviz.

**Comment by gavanderhoorn** [comment]
As I believe it's best to consider Gazebo a replacement for your hw and environment, introducing a direct sync between the MoveIt planning scene and Gazebo's internal worldstate doesn't seem like a good idea: you'd essentially be cheating ("hand of god"/"eye of god": as in real-life, MoveIt/your robot cannot get a list of collision objects from "the world").

The typical approach here would be to add a sensor to your robot that can detect (new) objects in the environment, such as a 3D camera, lidar or something else. That data can then be processed, and depending on whether you'd like to only update the MoveIt planning scene with objects or more complex (and dense) data such as octomaps/pointclouds, inserted into the planning scene as collision objects or by using one of the Octomap updater plugins for the planning scene.

Doing it this way your setup will work both in simulation and in the real world.

---

Edit: if you don't care about this and are willing to cheat, then perhaps [andreasBihlmaier/gazebo2rviz](https://github.com/andreasBihlmaier/gazebo2rviz) can help. Not sure it keeps track of objects spawned though.

**Comment by mehditlili** [comment]
Yes, you are right. But playing God is fun sometimes :p . I was just interested in seeing how the arm can operate and if it can correctly plan to avoid obstacles that I tell it about. The pointcloud plugin was my next step.
Thanks for the link I'll take a look.

**Comment by gavanderhoorn** [comment]
I'm not saying the plugin discussed here doesn't have its uses btw. I was as mystified as you (probably) are as to why it vanished somewhere between Hydro and Indigo.
