### ISSUE TITLE
Block laser plugins should produce PointCloud2 messages

### ISSUE THREAD

**Issue by bmagyar** [ros-simulation/gazebo_ros_pkgs#348]
or at least it should be configurable which type to produce so that different sensors can be easily replicated (like velodye).

**Comment by bmagyar** [comment]
I'd assign this to myself if I could :)

**Comment by ironmig** [comment]
@j-rivero, this was fixed

**Comment by kev-the-dev** [comment]
Duplicate of #50 (maintainers would appreciate this contribution so long as it maintains the current behavior as default)
