### ISSUE TITLE
New releases: indigo 2.4.9 and jade 2.5.1

### ISSUE THREAD

**Issue by j-rivero** [ros-simulation/gazebo_ros_pkgs#349]
Mainly to get support for compiling gazebo6 with C++11 (already committed but unreleased) I'm planning to release new versions of indigo and jade ros_gazebo_pkgs ASAP. @hsu @scpeters

**Comment by scpeters** [comment]
I think there's also quite a few commits in indigo-devel that haven't been merged forward into jade-devel

**Comment by j-rivero** [comment]
Indigo [pull request](ros/rosdistro/pull/9175) is ready

**Comment by j-rivero** [comment]
Jade [pull request](https://github.com/ros/rosdistro/pull/9177) is ready

**Comment by j-rivero** [comment]
Pull requests merged, all done.
