### ISSUE TITLE
[gazebo_ros]  Cannot change updateRate

### ISSUE THREAD

**Issue by talregev** [ros-simulation/gazebo_ros_pkgs#366]
Hi all,

In this file [turtlebot_gazebo.urdf.xacro](https://github.com/turtlebot/turtlebot/blob/indigo/turtlebot_description/urdf/turtlebot_gazebo.urdf.xacro)
There is using libgazebo_ros_openni_kinect.
And there is a definition of `updateRate`.
But As you can see at: [gazebo_ros_openni_kinect.cpp](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_plugins/src/gazebo_ros_openni_kinect.cpp),
There is no parameter `updateRate`

Can it be possible to implement an `updateRate` for camera plugin that we can easily change 
update rate of camera.

Thanks for you hard work,

Regards,
Tal Regev.

**Comment by lucasw** [comment]
It looks like the best practice is to use the sensor `<update_rate>` to set the rate and set the plugin `<updateRate>` to 0 (like in https://github.com/ros-simulation/gazebo_ros_demos/blob/master/rrbot_description/urdf/rrbot.gazebo).  The update_rate controls how often gazebo calls OnNewDepthFrame (or similar for other sensors), while in plugins that do have updateRate it is only able to throttle that down further, it certainly can't force it to go higher.  So it doesn't matter that gazebo_ros_openni_kinect doesn't even bother to read updateRate from the sdf.

I'm not sure why updateRate it exists at all, it is very confusing- maybe gazebo used to not have an update_rate and generated sensor callbacks at the full rate of the simulaton?  And if so are those old versions still getting supported?

**Comment by kev-the-dev** [comment]
The openni kinetic plugin actually does respect update rate because it inherits from GazeboRosCameraUtils (see its load function). But it is simpler to use the sensor update rate
