### ISSUE TITLE
[gazebo_ros_control] Jade release

### ISSUE THREAD

**Issue by vrabaud** [ros-simulation/gazebo_ros_pkgs#378]
Thx !

**Comment by j-rivero** [comment]
Ongoing, issue #395

**Comment by littlejohnyang** [comment]
Hopefully this will be released soon, because without gazebo_ros_control I am not sure if I should use ROS jade and latest version of gazebo for my new project.

**Comment by j-rivero** [comment]
Maybe @adolfo-rt can comment on this to help you with your plans

**Comment by alextoind** [comment]
@littlejohnyang I don't know if it may help you, but I am working with ROS Jade and `gazebo_ros_control` compiled by source with almost no problem (at least until now).

**Comment by fmessmer** [comment]
waiting for this, too!

**Comment by littlejohnyang** [comment]
I ended up compiling from source code. So far seems to be no problem. Trying out MoveIt at the same time now. Hopefully there will be no problem integrating everything together.

**Comment by j-rivero** [comment]
The 2.5.3 Jade version will include the gazebo_ros_control: ros/rosdistro#11044

Thanks for the feedback.
