### ISSUE TITLE
command "rosrun <package_name> gazebo not working?

### ISSUE THREAD

**Issue by mudasserzahid** [ros-simulation/gazebo_ros_pkgs#385]
Error. Gui Invalid arguments
/home/mudasser/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gazebo: 32: kill: invalid signal number or name: SIGINT

**Comment by peci1** [comment]
Works for me. What system do you use?

**Comment by mudasserzahid** [comment]
thanks i have solve that issue

**Comment by ipekkizil** [comment]
Hi, how did you solve it. @mudasserzahid
