### ISSUE TITLE
Release request for Gazebo 7

### ISSUE THREAD

**Issue by bchretien** [ros-simulation/gazebo_ros_pkgs#388]
Gazebo 7 was recently released, and it is now the default version on Arch Linux. Since the Gazebo-related packages are already patched for Gazebo 7, would it be possible to make a new release?

Thanks!

**Comment by alextoind** [comment]
I would appreciate it too: when trying to install `ros-jade-gazebo7-pkgs` it says that it depends on `ros-jade-gazebo7-plugins` which cannot be installed yet.

**Comment by v4hn** [comment]
:+1: Please release a new version of the repository into jade

**Comment by scpeters** [comment]
@j-rivero will be doing this soon.

**Comment by j-rivero** [comment]
The plan is as follow: 
- implement any kind of testing on the gazebo_ros_pkgs repo.
- release new version of gazebo_ros_pkgs into the usual ROS channels (needed for gazebo_ros_pkgs)
- release gazebo7_ros_pkg (all the metadata is in place)

**Comment by alextoind** [comment]
Thank you very much @j-rivero @scpeters.

If I may ask, is there an even roughly scheduled release date?

**Comment by j-rivero** [comment]
> If I may ask, is there an even roughly scheduled release date?

I would like to have it done before the end of the week.

**Comment by alextoind** [comment]
That's great! Thank you very much.

**Comment by j-rivero** [comment]
> That's great! Thank you very much.

Here we go: https://groups.google.com/a/osrfoundation.org/forum/#!topic/gazebo/8g_bJX12pO0

The thanks go to the great @scpeters which maintain the patches needed to keep the repo working with every new release of gazebo.

**Comment by bchretien** [comment]
@j-rivero perfect, thanks!
