### ISSUE TITLE
How to add a sensor to measure the relative information (e.g. position, distance) between different robots? 

### ISSUE THREAD

**Issue by libing64** [ros-simulation/gazebo_ros_pkgs#398]
I want to add a sensor plugins to measure the relative information between different robots, is there any guidance or tutorial for this?

**Comment by scpeters** [comment]
The following tutorial describes how to use some different sensors with `gazebo_ros`.  A ray sensor could find the distance to other objects:

http://gazebosim.org/tutorials?tut=ros_gzplugins

**Comment by libing64** [comment]
@scpeters  Can you explain more clearly? The distance obtained from ray sensor is the distance to the world, but how to get the distance to other robot?
Do I need to get other robot's position?

**Comment by libing64** [comment]
I have solved this problem, and add the wireless receiver sensor plugin to my project,
 https://github.com/libing64/hector_gazebo/tree/indigo-devel/hector_gazebo_plugins/include/hector_gazebo_plugins.

Thanks.
