### ISSUE TITLE
[gazebo_plugins] driver_base dependency is EOL

### ISSUE THREAD

**Issue by nicolaerosia** [ros-simulation/gazebo_ros_pkgs#402]
Hi,

driver_base [0] is EOL and gazebo_plugins has a build and runtime dependency on it (it needs the SensorLevels message).

[0] http://wiki.ros.org/driver_base

**Comment by jackieokay** [comment]
This will be resolved in Kinetic.

**Comment by j-rivero** [comment]
The dependency is not present in the kinetic-devel branch. Closing.
