### ISSUE TITLE
Gazebo7 compilation warnings

### ISSUE THREAD

**Issue by nicolaerosia** [ros-simulation/gazebo_ros_pkgs#406]
Hello,

I saw that for Kinetic release [0], Gazebo 7 will be used.
Can you please create a branch and I will create a PR to fix compilation warnings or you can just apply this:
https://github.com/nicolaerosia/gazebo_ros_pkgs/commit/5823bd500c3b0de12361b3df89e1a37ed70e1a9d

[0] https://github.com/ros-infrastructure/rep/blob/master/rep-0003.rst

**Comment by j-rivero** [comment]
I think that the warnings were fixed in pull #466.
