### ISSUE TITLE
[gazebo_plugins] camera sensor timestamp is one update old

### ISSUE THREAD

**Issue by lucasw** [ros-simulation/gazebo_ros_pkgs#408]
The camera message is getting sent out with a timestamp that is actually the last timestamp.  This is very apparent when setting update_rate to a low value, like 0.1.

https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_plugins/src/gazebo_ros_camera.cpp#L91

I think these first two functions need to pass in cur_time (or  `this->parentSensor_->GetLastUpdateTime()`?), right now the sensor_update_time_ is getting set to last_update_time_ in these functions: 

```
    this->PutCameraData(_image);
    this->PublishCameraInfo();
    this->last_update_time_ = cur_time;
```

I'll get a pr with a test together.

It looks like gazebo_ros_prosilica is doing it right, but gazebo_ros_multicamera, gazebo_ros_depth_camera, and gazebo_ros_openni_kinect are wrong.

http://answers.ros.org/question/229387/gazebo-camera-timestamp-is-10update_rate-out-of-date/

**Comment by lucasw** [comment]
Is there a reason updateRate exists, when the gazebo sensor update_rate already controls the rate of the sensor callback?

**Comment by lucasw** [comment]
I have a test now, and it works for

```
rostest gazebo_plugins camera.test
catkin_make run_tests_gazebo_plugins_rostest_test_camera_camera.test
```

But `catkin_make run_tests_gazebo_plugins` runs my test, which initially reports success, but then the next test never starts and camera.test fails overall because it runs out of time.  Do I need to do something more to shut down the test?

```
[ROSTEST]-----------------------------------------------------------------------

[gazebo_plugins.rosunit-set_model_state_test/FrameTest][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/lucasw/.ros/log/rostest-grr-7037.log
-- run_tests.py: verify result "/home/lucasw/catkin_ws/build/test_results/gazebo_plugins/rostest-test_set_model_state_test_set_model_state_test.xml"
Built target run_tests_gazebo_plugins_rostest_test_set_model_state_test_set_model_state_test.test
testcamera ... ERROR!
ERROR: max time [30.0s] allotted for test [camera] of type [gazebo_plugins/camera-test]
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/jade/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
--------------------------------------------------------------------------------

[ROSTEST WARNINGS]--------------------------------------------------------------

 * [/home/lucasw/catkin_ws/src/gazebo_ros_pkgs/gazebo_plugins/test/camera/camera.test] unknown <test> attribute 'require'

[ROSTEST]-----------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 1
 * FAILURES: 0
```

**Comment by janjachnik** [comment]
Nice work - I was having issues due to this bug and was about to fix it myself before I saw this. 

Note that the openni_kinect plugin also has the same problem.

**Comment by lucasw** [comment]
Check out #410 (which is stuck in limbo because the test infrastructure can't properly run the test?  Also it has gained some merge conflicts...).  Maybe you could make the same fixes for the kinect plugin in an independent pull request (I would guess very similar code and tests would work).

**Comment by helenol** [comment]
👍  Thanks for this! This issue is completely blocking for me, I'm so glad you already figured out the answer.

For anyone having trouble finding the diff from @lucasw's branch, here is the simple comparison:
https://github.com/ros-simulation/gazebo_ros_pkgs/compare/8a390af1e950fd417e3b7a6652d1e8c23ea929fd...lucasw:camera_timestamp_408

Main change is to swap from
`this->sensor_update_time_ = this->parentSensor->LastUpdateTime();`
to
`this->sensor_update_time_ = this->parentSensor->LastMeasurementTime();`

(and the Get() version of these for Gazebo versions before 7).

**Comment by j-rivero** [comment]
Thanks for the comment Helen. Could you verify if the pr #410 fix the issue for you?

**Comment by helenol** [comment]
Using openni_kinect plugin here, but making the same changes as in as in the depth camera in #410  fixed it there.

**Comment by lucasw** [comment]
Above are the rebased commits to kinetic version of the branch https://github.com/ros-simulation/gazebo_ros_pkgs/compare/kinetic-devel...lucasw:camera_timestamp_408_kinetic_devel based off the latest kinetic-devel.

**Comment by kev-the-dev** [comment]
Fixed in above mentioned merged PRs
