### ISSUE TITLE
Question about the block laser plugin

### ISSUE THREAD

**Issue by libing64** [ros-simulation/gazebo_ros_pkgs#412]
When I read the code of the block laser plugin, I have some questions.

a. the sign of z     

I think I should be r \* sin(pAngle) but here it is -r \* sin(pAngle), why?
point.x = r \* cos(pAngle) \* cos(yAngle);
point.y = r \* cos(pAngle) \* sin(yAngle);
point.z = -r \* sin(pAngle);

b.  why interpolating is needed?

why not use the raw value from the ray sensor but the interpolated value?

**Comment by kev-the-dev** [comment]
This was actually a bug, fixed in #582 in kinetic and up.
