### ISSUE TITLE
kinect plugin doesn't work in complex world?

### ISSUE THREAD

**Issue by libing64** [ros-simulation/gazebo_ros_pkgs#416]
I want to use the kinect plugin to generate some data to test the rgbdslam algorithm.
The plugin works well in some  worlds from [hector_gazebo](https://github.com/tu-darmstadt-ros-pkg/hector_gazebo) , however, it seems that the plugin doesn't work in complex world generated by myself (no rgb image and no depth is published) .
The world generated by myself is like this:
![complex_depth_scene](https://cloud.githubusercontent.com/assets/3192355/14227290/b892465c-f92c-11e5-8f4b-cacd19a81fd8.png)

Can anyone provide some help?

**Comment by libing64** [comment]
The kinect plugin doesn't work because the distance is beyond the "far" distance setting of kinect. After setting the far parameter to a bigger value, it works know.

**Comment by websailor** [comment]
I just use turtlebot3 simulate  project to validate  laser sensors in scene maps. When the robot moves forward or backward, the laser data is displayed correctly in RViz,once the robot turns, the laser sensor data is seriously distorted.  I think  the reason  is concered of raysensor  simulation   of  the gazebo raysensor plugin. Can anyone provide some help?  urdf file and map  pic is below!



[urdf.zip](https://github.com/ros-simulation/gazebo_ros_pkgs/files/2344112/urdf.zip)

![right_map](https://user-images.githubusercontent.com/6450895/44966030-71c69000-af6b-11e8-8a5f-23c092300481.png)
![wrong -maps](https://user-images.githubusercontent.com/6450895/44966031-725f2680-af6b-11e8-9c8a-90ed7e4fdc91.png)

**Comment by chapulina** [comment]
@websailor , https://answers.ros.org is a better place for this kind of question. It looks like you're having a problem with your fixed frame.
