### ISSUE TITLE
Release new version: indigo 2.4.11

### ISSUE THREAD

**Issue by wkentaro** [ros-simulation/gazebo_ros_pkgs#418]
I need below commits:
- https://github.com/ros-simulation/gazebo_ros_pkgs/commit/9f568a2d95f59ef3918c6008e13617d226004d46
- https://github.com/ros-simulation/gazebo_ros_pkgs/commit/0599923207b4942bafe13b9b90fb911c20589a6a

**Comment by wkentaro** [comment]
Could you please release new version?

**Comment by furushchev** [comment]
+1
These fixes are necessary for working gazebo with kinect.

**Comment by jackieokay** [comment]
We'll release a new version for Indigo and Jade tomorrow when we do the initial release for Kinetic. Sorry that we didn't get around to this before the most recent sync with Indigo!

**Comment by j-rivero** [comment]
2.4.11 https://github.com/ros/rosdistro/pull/12158
