### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by jackieokay** [ros-simulation/gazebo_ros_pkgs#425]
This will be a team effort with: @scpeters @hsu @wjwwood @hugomatic @chapulina @j-rivero @caguero 

Here are a few tasks that I can think of off the top of my head:
- [x] Make kinetic-devel branch
- [x] Update Travis so that branches targeting kinetic-devel don't fail automatically due to missing rosdep keys
  - #431
- [x] Set up pull request testing on the farm (ros/rosdistro#11294)
- [x] Update to Gazebo 7 (that's the default system version of Gazebo in Xenial, yes?)
  - #426
- [x] Add @j-rivero's name in the package.xml as a maintainer ;)
- [x] Check if pending PRs should go into the Kinetic release (some could probably get into both Jade and Kinetic?)
- [x] Merge all PRs in the [kinetic milestone](https://github.com/ros-simulation/gazebo_ros_pkgs/milestones/kinetic%20release)
- [ ] Test if there are build/runtime regressions for the combination of existing code/Gazebo 7/Xenial control_toolbox dependency
  - [ ] indigo
  - [x] jade
  - [x] kinetic
- [ ] Remove warnings from kinetic
- [x] Fix changelog in jade
- [ ] Make tags and bloom release
  - Might as well do an Indigo and Jade release when we do this, @wkentaro asked for this in #418
  - [x] release kinetic !!!
  - [x] release jade
  - [ ] release indigo

**Comment by wjwwood** [comment]
Let me know how I can help. Not sure where I fit in.

Gazebo7 is the version for Kinetic (Wily + Xenial): http://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021

**Comment by scpeters** [comment]
Ok, the latest indigo release is [2.4.10](https://github.com/ros-simulation/gazebo_ros_pkgs/releases/tag/2.4.10), and there have been a [few pull requests merged since then](https://github.com/ros-simulation/gazebo_ros_pkgs/compare/2.4.10...indigo-devel).

Let's triage the open pull requests to see if anything needs to go into `indigo-devel`, then merge them forward to `jade-devel`, make new releases of indigo and jade, then rebase the kinetic branch off of the jade tag.

**Comment by jackieokay** [comment]
If you merge a PR to Kinetic with new features/major behavioral changes, make sure to edit the Migration guide:

http://wiki.ros.org/kinetic/Migration

**Comment by j-rivero** [comment]
> If you merge a PR to Kinetic with new features/major behavioral changes, make sure to edit the Migration guide:
> 
> http://wiki.ros.org/kinetic/Migration

Done:  http://wiki.ros.org/kinetic/Migration#Gazebo_Simulator

**Comment by jackieokay** [comment]
#426 was merged (with the CATKIN_IGNORE in gazebo_ros_control) so if you rebase branches that target kinetic_devel, you should be able to use pull request testing with the ROS build farm to see if your code still builds on Xenial/with Gazebo 7. Let us know if you have questions about how to do that. Note that the Travis job will still fail for anything that targets kinetic_devel, #431 will remove it.

**Comment by jackieokay** [comment]
actually Dirk just told me that the pull request tester automatically merges with the target branch before, so you might not even need to rebase before using PR testing

**Comment by bmagyar** [comment]
Thought you guys may appreciate that `control_toolbox` is released as well as `ros_controllers` ;)
Let me know if there's something missing that I can help with.

**Comment by jackieokay** [comment]
Yep, we've un-ignored gazebo_ros_control for Kinetic as of this morning: ros-simulation/gazebo_ros_pkgs#456

**Comment by j-rivero** [comment]
Closing this issue since it served as tracker from the times of releasing the first kinetic packages.
