### ISSUE TITLE
VMWare throwing an error when launching gazebo

### ISSUE THREAD

**Issue by badrobit** [ros-simulation/gazebo_ros_pkgs#457]
When attempting to run Gazebosim as installed by ros kinetic in Ubuntu 16.04 I get the following error: 

```
mroscoe@ubuntu:~$ gazebo
VMware: vmw_ioctl_command error Invalid argument.
```

I have not seen this being thrown by any other 3D program such as RVIZ or OctoVis.

**Comment by j-rivero** [comment]
Looks like the error it is with gazebo itself when running on vmware. Using the [gazebo upstream issue tracker](https://bitbucket.org/osrf/gazebo/) looks the right place to report issues for gazebo itself.

Please attach there the version of gazebo used (probably 7.0.0), the version and flavour of vmware and the output of glxinfo.

Thanks!
