### ISSUE TITLE
Cleanup of commented blocks in ros_control plugin

### ISSUE THREAD

**Issue by jbohren** [ros-simulation/gazebo_ros_pkgs#47]
After I merged ros_control_gazebo and gazebo_ros_control, there were a lot of commented-out debug and experimental blocks, could you clean these up, or move them to a branch for experimentation?

Debug: https://github.com/osrf/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/ros_control_plugin.cpp#L103

??: https://github.com/osrf/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/ros_control_plugin.cpp#L192

Debug: https://github.com/osrf/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/ros_control_plugin.cpp#L302

Experimental: https://github.com/osrf/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/ros_control_plugin.cpp#L306

**Comment by davetcoleman** [comment]
Most of this has been cleaned up (and used) with my latest pull request.

You were the one who pushed my work-in-progress into gazebo_ros_pkgs :)

**Comment by jbohren** [comment]
Haha, cool. It was just a loose end I meant to tie up. Feel free to close it if this is all dealt with in https://github.com/osrf/gazebo_ros_pkgs/pull/46
