### ISSUE TITLE
Help needed ...

### ISSUE THREAD

**Issue by ghost** [ros-simulation/gazebo_ros_pkgs#471]
Hi
I'm new to gazebo ros and i'm trying to adapt the **gazebo_ros_skid_steer_drive.cpp** to my robot but i'm having some troubles so i have some questions:
1. where to find **robotNamespace** (line 81) **if(!_sdf->HasElement("robotNamespace"))** in the SDF file, it's the model name or something else? for example in my SDF i have this

```
<model name="KobraRobot">
      <plugin name="kobra_robot" filename="libkobra_robot.so"/>
```

so robotNamespace=KobraRobot ?
1.  second question, why this have two different names 

```
this->left_front_joint_name_ = "**left_front_joint**";
if(!_sdf->HasElement("**leftFrontJoint**")) 
```

 what to put in **!_sdf->HasElement("")** the name of the joint in the SDF file or the name of the child inside the joint, my SDF file is something like this

```
<joint name="right_rear_joint" type="revolute">
        <parent>link_body</parent>
        <child>link_wheel_rear_right</child>
        ...
```

thanks to all (sorry for english)

**Comment by j-rivero** [comment]
Hello:

For questions about ROS, the community uses the great http://answers.ros.org/ site. We leave the issue tracker for bug reports or other works related to the code but not for questions. Please resubmit your question there.

Thanks.
