### ISSUE TITLE
Release Request 2.5.6

### ISSUE THREAD

**Issue by furushchev** [ros-simulation/gazebo_ros_pkgs#474]
Could you release new version for indigo / jade?
Almost 2 months have passed since the last release and there is important not yet released:
- https://github.com/ros-simulation/gazebo_ros_pkgs/commit/df82c78fb5ef20ea463dc8443b140161acee13da

**Comment by j-rivero** [comment]
I released [2.4.11 for Indigo](https://github.com/ros/rosdistro/pull/12158) one week ago.
For jade, I'm waiting to merge https://github.com/ros-gbp/gazebo_ros_pkgs-release/pull/8. As soon as it is done, I will fire up bloom.

**Comment by furushchev** [comment]
@j-rivero Thanks for information!

**Comment by j-rivero** [comment]
After some conflicts with versioning, I just released 2.6.0 for Jade: https://github.com/ros/rosdistro/pull/12271 with the latest changes. That should be enough, feel free to reopen the issue if something is still needed.

Thanks.

**Comment by furushchev** [comment]
@j-rivero Thanks for informing!
