### ISSUE TITLE
Superfluous error messagy while calling /gazebo/get_world_properties 

### ISSUE THREAD

**Issue by ipa-srd-rd** [ros-simulation/gazebo_ros_pkgs#475]
When you call the `/gazebo/get_world_properties` service, a superfluous error message is printed to the screen:

Error [gazebo_ros_api_plugin.cpp:907] disablign rendering has not been implemented, rendering is always enabled

Despite the wrong wording, I'm not quite sure if it's necessary to print an error message without any check or failure. I hope you could fix this for ros indigo. Below the link to the codeline containing the error output.

[https://github.com/ros-simulation/gazebo_ros_pkgs/blob/1eff1d6f5ccd1b3d0a85cf50c97794471cd3aebe/gazebo_ros/src/gazebo_ros_api_plugin.cpp#L929](url)

**Comment by mikaelarguedas** [comment]
+1
permalink:
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/49201f64e1885901120a01172f15e268874a98ab/gazebo_ros/src/gazebo_ros_api_plugin.cpp#L980

**Comment by chapulina** [comment]
Removed on #747
