### ISSUE TITLE
SolveSpace support

### ISSUE THREAD

**Issue by ghost** [ros-simulation/gazebo_ros_pkgs#476]
Can you add support to SolveSpace? (2D/3D cad) 
- http://github.com/solvespace/solvespace

Or can you give quick tutorial how prepare model in SolveSpace (that support different formats for export) for simulation in your tool.

**Comment by j-rivero** [comment]
Hello @Symbian9:

This repository hosts the code for the ROS wrapper of Gazebo simulator. You probably want to submit your request to the [Gazebo upstream issue tracker](https://bitbucket.org/osrf/gazebo/issues). Thanks.
