### ISSUE TITLE
gazebo_ros_control: namespace tag name

### ISSUE THREAD

**Issue by jbohren** [ros-simulation/gazebo_ros_pkgs#48]
Should the namespace tag in the gazebo_ros_control plugin XML be clearer than "robotNamespace" since it only affects the ros_control plugin? Maybe "rosNamespace" or "controllerNamespace" or something like that?

Inline TODO: https://github.com/osrf/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/ros_control_plugin.cpp#L112

**Comment by jbohren** [comment]
Fixed in #46

**Comment by davetcoleman** [comment]
`robotNamespace` is what Gazebo uses elsewhere for plugins that have a `/MYROBOT/` prefix, so I think sticking to this standard is nice.

On this topic, what do you think about having everything simply prefixed by `/MYROBOT`? i.e. when I launch the demo rrbot I see in the rostopic list:

```
/rrbot/camera1/camera_info
/rrbot/camera1/image_raw
/rrbot/joint1_position_controller/command
/rrbot/joint1_position_controller/state
/rrbot/joint2_position_controller/command
/rrbot/joint2_position_controller/state
/rrbot/laser/scan
```

And rosparam:

```
/rrbot/camera1/camera_info
/rrbot/camera1/image_raw
/rrbot/joint1_position_controller/command
/rrbot/joint1_position_controller/state
/rrbot/joint2_position_controller/command
/rrbot/joint2_position_controller/state
/rrbot/laser/scan
```

I don't think we need the `ros_control` part.

**Comment by jbohren** [comment]
Yeah, I think it's fine without `ros_control` in the namespace. Also, when I first read `/MYROBOT/` I interpreted it as a literal. In the documentation, we probably want to make it more obviously a placeholder that you never actually see like `/ROBOT_NAME/` or even better `/MODEL_NAME/`.
