### ISSUE TITLE
help to edit libgazebo_ros_bumper source

### ISSUE THREAD

**Issue by Ma2oud** [ros-simulation/gazebo_ros_pkgs#494]
Dear developers

I'm going to validate gazebo and ROS contact and 6 axis force/torque sensors. I have currently studied 6 axis force torque sensor using a simple inverted pendulum. I compared 6 axis forces and torques outputs with the ones that I calculate using dynamic model of the inverted pendulum. Unfortunately, I realized that force and torque values are abnormal and noisy (although I set Gaussian noise for the sensor to zero) 

After getting abnormal data from 6 axis force torques, I decided to use libgazebo_ros_bumper as contact sensor. Now my problem in evaluating output of this sensor is that the size of contact state is very large (e. g. 34 contact point even in simulating contact between sphere and ground). That is why I want to edit source code of libgazebo_ros_bumper to sum up all contact force and make one advertise one total wrench and force... Am new to ROS and gazebo, can someone here help me to do this??

Thanks for your attention

**Comment by j-rivero** [comment]
Seems like the question is strictly about gazebo even if ROS is involved in the implementation. You can probably get more attention and better answers in the [gazebo Q&A site](http://answers.gazebosim.org/). Would you mind re-posting it there? Thanks!
