### ISSUE TITLE
Namespacing causes sigterm on exit

### ISSUE THREAD

**Issue by el3ment** [ros-simulation/gazebo_ros_pkgs#507]
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/f03ddc2bcc66b4bac6ed136ea0beb1807a4bacfb/gazebo_ros/src/gazebo_ros_api_plugin.cpp#L1985

I think this line (and the next) are supposed to use the gazebo_namespace, not just be hardcoded to /gazebo

The issue is that when using a namespace, we get this

waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...

Because it will never be advertised. When killing the agent, gazebo waits for a long time, and eventually raises a sigterm and dies

**Comment by kev-the-dev** [comment]
Good catch. This actually would break  the physics reconfigure feature when in a namespace. Fixed in #732
