### ISSUE TITLE
gazebo_ros_control is failing to build on wily and jessie but ok on xenial

### ISSUE THREAD

**Issue by tfoote** [ros-simulation/gazebo_ros_pkgs#513]
http://repositories.ros.org/status_page/ros_kinetic_dj.html?q=REGRESSION
http://repositories.ros.org/status_page/ros_kinetic_default.html?q=REGRESSION

It looks like this is a regression recently and I see that ros_control was released recently. https://github.com/ros/rosdistro/pull/13320 by @bmagyar

**Comment by bmagyar** [comment]
Weird...The logs suggest it's related to the unboosting efforts over at urdf.
Related PR on `ros_control`: https://github.com/ros-controls/ros_control/pull/251

It seems to me that the most relevant error is this:
```
/opt/ros/kinetic/include/joint_limits_interface/joint_limits_urdf.h:51:28: error: ‘JointConstSharedPtr’ is not a member of ‘urdf’
```

How do other dependants of urdf do?

**Comment by tfoote** [comment]
@wjwwood what was the approach you recommended from testing with rviz?

**Comment by wjwwood** [comment]
The urdf package has a comparability header now.

**Comment by bmagyar** [comment]
Is there any action I need to take? Please point me at something :)

**Comment by tfoote** [comment]
@bmagyar I think that the join_limits_interface needs to include this newly added header in urdf: https://github.com/ros/robot_model/commit/f5a3b8048c9fb4767ebd20b0cd80531c81522017 Which should give you the pointer referenced on all platforms. It looks like the same issue is breaking the schunk_canopen_driver: http://build.ros.org/view/Kbin_uW64/job/Kbin_uW64__schunk_canopen_driver__ubuntu_wily_amd64__binary/28/console

**Comment by bmagyar** [comment]
Thanks! I've submitted a patch, hoping to get some results from jenkins soon, then I'l do the release.

**Comment by tfoote** [comment]
This was resolved a while ago.
