### ISSUE TITLE
gazebo_ros_camera_utils is resolving the tf_prefix twice

### ISSUE THREAD

**Issue by dcconner** [ros-simulation/gazebo_ros_pkgs#526]
`// resolve tf prefix
  std::string key;
  if(this->rosnode_->searchParam("tf_prefix", key)){
    std::string prefix;
    this->rosnode_->getParam(key, prefix);
    this->frame_name_ = tf::resolve(prefix, this->frame_name_);
  }

  this->itnode_ = new image_transport::ImageTransport(*this->rosnode_);
  
  // resolve tf prefix
  this->tf_prefix_ = tf::getPrefixParam(*this->rosnode_);
  if(this->tf_prefix_.empty()) {
      this->tf_prefix_ = this->robot_namespace_;
      boost::trim_right_if(this->tf_prefix_,boost::is_any_of("/"));
  }
  this->frame_name_ = tf::resolve(this->tf_prefix_, this->frame_name_);
`

This results in camera topics being published with double prefix for frame_id

**Comment by IanTheEngineer** [comment]
+1 looks like there is a missing cherry-pick in the `kinetic-devel` branch. Relates to #460, #463, #464
