### ISSUE TITLE
Can't setup GAZEBO_PLUGIN_PATH with package.xml

### ISSUE THREAD

**Issue by ghost** [ros-simulation/gazebo_ros_pkgs#531]
Hello,

My package.xml contains the following `<export>` tags :

    <export>
        <gazebo_ros gazebo_model_path="${prefix}/models"/>
        <gazebo_ros gazebo_plugin_path="${prefix}/plugins"/>
    </export>

But it appears that when I run a .launch file from the package, only GAZEBO_MODEL_PATH is set, and not GAZEBO_PLUGIN_PATH. Thus, my models load, but not my plugin.

What am I doing wrong ?

(More detail on what I am trying to achieve [here](http://answers.gazebosim.org/question/15200/cant-load-plugin-with-roslaunch/), but it boils down to this current issue)

Cheers

**Comment by vincentrou** [comment]
Did you try to put them on the same gazebo_ros tag ?

**Comment by ghost** [comment]
Thank you for your answer.

Not sure what I tried at the time, but now I did. Still no plugin is found.

**Comment by kev-the-dev** [comment]
Looking at [the code](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_ros/src/gazebo_ros_paths_plugin.cpp#L75), the tag that is recognized by the path plugin is actually "plugin_path" not "gazebo_plugin_path". Try:
```<gazebo_ros plugin_path="${prefix}/plugins"/>``` instead. This is inconsistent with the other tags and should probably be changed... did you find any documentation that led you to believe it is gazebo_plugin_path?

**Comment by kev-the-dev** [comment]
As this is just a usage issue, closing.
