### ISSUE TITLE
organization icon for ros-simulation

### ISSUE THREAD

**Issue by jbohren** [ros-simulation/gazebo_ros_pkgs#54]
![ros_simulation_dots](https://f.cloud.github.com/assets/1253450/720596/34b1e802-dfc5-11e2-8b21-dcc20b7ea6ac.png)

**Comment by davetcoleman** [comment]
@dirk-thomas i believe your email is linked to the https://github.com/ros-simulation account, can you add this please (via gravatar)?

**Comment by davetcoleman** [comment]
And nice work Jonathan!

**Comment by dirk-thomas** [comment]
done.
