### ISSUE TITLE
‘LightPtr’ is not a member of ‘gazebo::physics’

### ISSUE THREAD

**Issue by wangzhaodong123** [ros-simulation/gazebo_ros_pkgs#575]
When I catkin_make my work_space , the problem happened:
‘LightPtr’ is not a member of ‘gazebo::physics’
why? can you help me ? Thank you .

**Comment by j-rivero** [comment]
I think that your facing a problem migration from one gazebo version to another, probably from gazebo8 to gazebo9. There is a good document in [gazebo upstream project](https://bitbucket.org/osrf/gazebo/src/default/Migration.md?fileviewer=file-view-default) describing the deprecations and the replacement functions.

For this kind of questions related to fails in compilation, please use http://answers.gazebosim.org.

**Comment by wangzhaodong123** [comment]
Thanks for advise.After installing gazebo7, I met another problem when i catkin_make my work_space:
Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake
Could you tell me why? Thank you.

**Comment by scpeters** [comment]
@wangzhaodong123 did you install `libgazebo7-dev`? I believe that has the cmake config files.

**Comment by wangzhaodong123** [comment]
@scpeters @j-rivero Thank you very much,and i solved the problem just now.Thank you.
