### ISSUE TITLE
Gazebo ROS Paths

### ISSUE THREAD

**Issue by davetcoleman** [ros-simulation/gazebo_ros_pkgs#58]
Why is there a gazebo_media_path, plugin_path, and gazebo_model_path in `gazebo_ros_paths_plugin.cpp`? What are those used for, where, and do we need all three?

@hsu

**Comment by hsu** [comment]
they map to parameters in gazebo:
- `gazebo_model_path` --> [GAZEBO_MODEL_PATH](https://bitbucket.org/osrf/gazebo/src/222b5b368663a4ad7a8cd3acd8c83d1a5ea652ca/gazebo/common/SystemPaths.cc?at=default#cl-137)
- `gazebo_media_path` --> [GAZEBO_RESOURCE_PATH](https://bitbucket.org/osrf/gazebo/src/222b5b368663a4ad7a8cd3acd8c83d1a5ea652ca/gazebo/common/SystemPaths.cc?at=default#cl-165)
- `gazebo_plugin_path` --> [GAZEBO_PLUGIN_PATH](https://bitbucket.org/osrf/gazebo/src/222b5b368663a4ad7a8cd3acd8c83d1a5ea652ca/gazebo/common/SystemPaths.cc?at=default#cl-192)

**Comment by davetcoleman** [comment]
I ask because of this pull request https://github.com/ros-simulation/gazebo_ros_pkgs/pull/69

**Comment by davetcoleman** [comment]
Pull request merged.
