### ISSUE TITLE
gazebo_ros_block_laser Still has inverted Z Axis data

### ISSUE THREAD

**Issue by RDaneelOlivav** [ros-simulation/gazebo_ros_pkgs#593]
It seems that in th gazebo_ros_block_laser installed by default, the Z axis is bugged and it appears always inverted that data registered.

Does anyone know if this is fixed and how to update the code to add that fix?

The last know response to this was in this post and it seems the solution is modifieng the code and compiling the lib manually. Is there any fix already?
http://answers.gazebosim.org/question/5067/how-to-simulate-a-velodyne-sensor/

**Comment by ompugao** [comment]
see https://github.com/ros-simulation/gazebo_ros_pkgs/issues/529

**Comment by j-rivero** [comment]
the official release is ongoing: https://github.com/ros/rosdistro/pull/15350
