### ISSUE TITLE
Error parsing XML in file when trying to open saved Gazebo file

### ISSUE THREAD

**Issue by lizixroy** [ros-simulation/gazebo_ros_pkgs#599]
Guys, 

Pretty new to Gazebo so this might be a dumb question. I was following the tutorial to create vehicle in Gazebo: http://gazebosim.org/tutorials?cat=guided_b&tut=guided_b3

I saved the progress to come back to it later, but I cannot find a way to open the saved files (model.config & model.sdf) using gazebo from command line.

When I do this: 
gazebo roys_first_car/
I got the following error:
Error [parser.cc:293] Error parsing XML in file [/Users/Roy/model_editor_models/roys_first_car/]: Failed to open file

I cannot find a way to load the saved file in GUI either.

Thoughts?

Many thanks in advance.

Roy

**Comment by j-rivero** [comment]
This issue tracker is specific for the problems related to the ROS Gazebo wrappers. For questions about  Gazebo, please refer to http://answers.gazebosim.org
