### ISSUE TITLE
launch model on gazebo but the model is floating on air

### ISSUE THREAD

**Issue by Ash1020** [ros-simulation/gazebo_ros_pkgs#648]
I created model by using urdf, and it was launch correctly on Rviz simulator.
I want to launch it on Gazebo and I created the launch file but it wasn't launch correctly.
I can launch the model on Gazebo, but it seems to be on the air.
The parameter of Z position is about 4.98 and I can't change that value.
How can I fit the model on the ground?

**Comment by j-rivero** [comment]
Could you please post your URDF model and launch file?

**Comment by Ash1020** [comment]
Thank you for your kindness. I success to launch correctly.
I missed to adjust collision parameter.
