### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by davetcoleman** [ros-simulation/gazebo_ros_pkgs#68]
```
CMake Error at CMakeLists.txt:35 (find_package):
  Could not find module Findgazebo.cmake or a configuration file for package
  gazebo.

  Adjust CMAKE_MODULE_PATH to find Findgazebo.cmake or set gazebo_DIR to the
  directory containing a CMake configuration file for gazebo.  The file will
  have one of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake



CMake Error at CMakeLists.txt:36 (find_package):
  Could not find module FindSDF.cmake or a configuration file for package
  SDF.

  Adjust CMAKE_MODULE_PATH to find FindSDF.cmake or set SDF_DIR to the
  directory containing a CMake configuration file for SDF.  The file will
  have one of the following names:

    SDFConfig.cmake
    sdf-config.cmake
```

@tfoote we set this up today together, what do you think went wrong?

**Comment by tfoote** [comment]
Where's the log?

**Comment by davetcoleman** [comment]
[Jenkins](http://jenkins.willowgarage.com:8080/job/ros-hydro-gazebo-plugins_binarydeb_precise_i386/11/console)

**Comment by tfoote** [comment]
@dirk-thomas  does this look right for the location of the cmake files

```
$dpkg -L gazebo-prerelease | grep cmake
/usr/share/gazebo/cmake
/usr/share/gazebo/cmake/gazebo-config.cmake
$dpkg -L sdformat | grep cmake
/usr/share/sdformat/cmake
/usr/share/sdformat/cmake/SDFConfig.cmake
```

**Comment by tfoote** [comment]
The problem is that it installed ros-hydro-gazebo not gazebo-prerelease.  I'll look into it shortly. i've got to go eat dinner

**Comment by tfoote** [comment]
removed: https://github.com/ros/rosdistro/pull/1307

**Comment by tfoote** [comment]
You will need to rerun bloom to make a debian increment and fix the dependencies.

**Comment by davetcoleman** [comment]
I ran

```
git-bloom-release hydro
git push --all && git push --tags
```

Is that enough?

**Comment by davetcoleman** [comment]
Or do I need this too? https://github.com/ros/rosdistro/pull/1310

**Comment by tfoote** [comment]
exactly, there's a ticket for bloom to be able to make that after running git-bloom-release https://github.com/ros-infrastructure/bloom/issues/184

**Comment by wjwwood** [comment]
You should use `bloom-release` instead of `git-bloom-release`.

**Comment by davetcoleman** [comment]
It was `git-bloom-release` until June 20th - maybe note that it has changed on the wiki page?

**Comment by wjwwood** [comment]
I don't believe it was, but if you know where that reference is it might have been missed when I updated it months ago...

**Comment by davetcoleman** [comment]
its on [this](http://www.ros.org/wiki/bloom/Tutorials/FirstTimeRelease?action=recall&rev=19) old page, but its been removed :)

**Comment by wjwwood** [comment]
@davetcoleman That is for the first release, for subsequent releases: http://www.ros.org/wiki/bloom/Tutorials/ReleaseCatkinPackage

**Comment by wjwwood** [comment]
I think I can update the first release to use `bloom-release` as well though, that would be more consistent.

**Comment by davetcoleman** [comment]
It builds now so closing this issue.
