### ISSUE TITLE
gazebo ros control using joint velocity interface can't work with gazebo 9 with dart physics engine

### ISSUE THREAD

**Issue by jacknlliu** [ros-simulation/gazebo_ros_pkgs#690]
Gazebo ros control can't work with gazebo 9 with dart physics engine.  The robot defined from URDF can't keep joint position in this context.

We found that ros control using joint velocity interface will write joint command use [` sim_joints_[j]->SetParam("vel")`](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_ros_control/src/default_robot_hw_sim.cpp#L345), but the `vel` key-value is not implement in gazebo dart engine, see [ gazebo / physics / dart](https://bitbucket.org/osrf/gazebo/src/25df4fb10d33a9baaccdf4d48f99ca7fd4f26584/gazebo/physics/dart/DARTJoint.cc?at=default&fileviewer=file-view-default#DARTJoint.cc-559) .

So the velocity interface will not work correctly with dart engine.

**Comment by jacknlliu** [comment]
Could we get the physics engine name from gazebo API?  or we should file an issue with gazebo repo.

**Comment by j-rivero** [comment]
> Could we get the physics engine name from gazebo API? or we should file an issue with gazebo repo.

It should be perfectly possible, like [in this gazebo test](https://bitbucket.org/osrf/gazebo/src/25df4fb10d33a9baaccdf4d48f99ca7fd4f26584/test/integration/joint_spawn.cc?at=default&fileviewer=file-view-default#joint_spawn.cc-278)
