### ISSUE TITLE
gazebo_ros_diff_drive should add a 'enable_odom_tf' parameter

### ISSUE THREAD

**Issue by sychaichangkun** [ros-simulation/gazebo_ros_pkgs#692]
I want to use `robot_pose_ekf` package which merges IMU, VO and Odometry and outputs the tf odom -> base_footprint.  But diff_drive plugin is always broadcasting the tf odom -> base_footprint,  these two transform conflicts.  I think there should be a param  to enable or disable the tf in diff drive plugin.

**Comment by sychaichangkun** [comment]
I read the source code of gazebo_ros_diff_drive.cpp and found that in the function `GazeboRosDiffDrive::publishOdometry()`, odom tf is broadcasted and odom topic is published at the same time. There is one param `publishTf`, but it turns on/off the topic and tf altogether.
In my case I just want the /odom topic, as the input of `robot_pose_ekf`, but I dont want tf of odom->base_link, which `robot_pose_ekf`  also broadcasts.

I suggest to add two params `publishOdomTF` and `publishOdomTopic` , that would be more clear for users. And I would like to fix the bug.

**Comment by KrzysztofZurad** [comment]
Hi, any progress on this one? I have the same problem to solve, need to fuse data with imu and use robot_localization.

**Comment by j-rivero** [comment]
> Hi, any progress on this one? I have the same problem to solve, need to fuse data with imu and use robot_localization.

Thanks for the proposal guys, seems reasonable to me. Feel free to make the necessary changes, be sure of not changing the default behavior for the rest of users (not hard, just leave the new feature disabled by default).

**Comment by kev-the-dev** [comment]
Merged. Can close issue now.
