### ISSUE TITLE
Release for Melodic 

### ISSUE THREAD

**Issue by j-rivero** [ros-simulation/gazebo_ros_pkgs#696]
Hi all:

It is time to think on creating the `melodic-devel` branch from `lunar-devel`. Disruptive changes can be made at this time like those that modifies the API and the topic/service interface. Please speak up if you have in mind anything that needs to be merged.

We will need `ros_controls` but I believe that @bmagyar will be taking care of it during the next days.

//cc @clalancette

**Comment by bmagyar** [comment]
We've been ready for a while now ;)

**Comment by j-rivero** [comment]
`melodic-devel`branch has been created. Making disruptive changes (API or changes in the ROS topic, service, params) now.

**Comment by j-rivero** [comment]
Currently block by the lack of some dependencies: `ros-melodic-cv-bridge, ros-melodic-diagnostic-updater, ros-melodic-pcl-conversions`:
 * cv-bridge: https://github.com/ros-perception/vision_opencv/issues/208
 * pcl-conversions: https://github.com/ros-perception/pcl_conversions/issues/28
 * diagnostic-update: https://github.com/ros/diagnostics/issues/81

**Comment by clalancette** [comment]
All of the dependencies for this are now in Melodic, so I think we should be good to go to release this.  Thanks in advance!

**Comment by j-rivero** [comment]
gazebo_ros_pkgs have been released. In the `ros-shadow-fixed` directory.
