### ISSUE TITLE
Gazebo plugin documentation

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-simulation/gazebo_ros_pkgs#737]
Some of the documentation in Gazebo plugins  source code is  too short to explain the other user about what the plugins does and how to use it. Is there any source  that  contain brief documentation of  Gazebo plugins?

**Comment by kev-the-dev** [comment]
Checkout [the ros plugins tutorial](http://gazebosim.org/tutorials?tut=ros_gzplugins) from the gazebo tutorials.

**Comment by AchmadFathoni** [comment]
@ironmig thank you, but the site that you mentioned only cover view part about the plugins. Maybe I demand service too much for a open source project.
