### ISSUE TITLE
Gazebo needs to include tbb in its GAZEBO_LIBRARIES

### ISSUE THREAD

**Issue by davetcoleman** [ros-simulation/gazebo_ros_pkgs#74]
To fix [error](http://jenkins.willowgarage.com:8080/job/ros-hydro-gazebo-plugins_binarydeb_precise_i386/25/consoleFull)

```
/usr/include/gazebo-1.9/gazebo/transport/Connection.hh:20:22: fatal error: tbb/task.h: No such file or directory
```

Use this code snippet?

```
 #################################################                                                                                                     
  # Find TBB                                                                                                                                            
  pkg_check_modules(TBB tbb)
  if (NOT TBB_FOUND)
    message(STATUS "TBB not found, attempting to detect manually")

    find_library(tbb_library tbb ENV LD_LIBRARY_PATH)
    if (tbb_library)
      set(TBB_FOUND true)
      set(TBB_LIBRARIES ${tbb_library})
    else (tbb_library)
      BUILD_ERROR ("Missing: TBB - Threading Building Blocks")
    endif(tbb_library)
  endif (NOT TBB_FOUND)
```

**Comment by tfoote** [comment]
This is just an issue of missing libtbb-dev as a dependency. Ticketed upstream at: https://bitbucket.org/osrf/gazebo/issue/779/missing-dependency-export-for-tbb

**Comment by davetcoleman** [comment]
This issue should not be closed until commit https://github.com/ros-simulation/gazebo_ros_pkgs/commit/08a08914dc9af65f14ecf6a8e6b86529f3fa649c is removed

**Comment by davetcoleman** [comment]
Fixed in gazebo here: https://bitbucket.org/osrf/gazebo-release/issue/40

**Comment by davetcoleman** [comment]
Fixed in commit https://github.com/ros-simulation/gazebo_ros_pkgs/commit/05818149769e30756d6726b3a6edf9c3b269a12f
