### ISSUE TITLE
error releasing custom plugin package

### ISSUE THREAD

**Issue by piyushk** [ros-simulation/gazebo_ros_pkgs#76]
Package: https://github.com/utexas-bwi/segbot_simulator/tree/stable/segbot_gazebo_plugins

Jenkins log: http://jenkins.willowgarage.com:8080/job/ros-hydro-segbot-gazebo-plugins_binarydeb_quantal_amd64/10/consoleFull

I am a bit confused by this one. The console log says that `libcegui-mk2-0.7.6` was installed. Any thoughts on debugging this?

**Comment by gerkey** [comment]
See [gazebo-release #40](https://bitbucket.org/osrf/gazebo-release/issue/40).

I'll roll a gazebo-prerelease 1.9.4 release with the updated deb dependencies.

**Comment by piyushk** [comment]
@gerkey Thanks!! I didn't realize that the dev version was not being installed. I am a bit confused as to how gazebo_plugins had a successful build. I guess the dependency issue did not exist then.

**Comment by gerkey** [comment]
Maybe gazebo_plugins isn't including the offending Gazebo header.

**Comment by davetcoleman** [comment]
Your `gazebo_ros_video` plugin is pulling in `gazebo/rendering/GUIOverlay.hh` which I believe none of the gazebo_ros_plugin packages do, so you found a new bug. Btw, what does gazebo_ros_video do and is it stable?

Please close this ticket once the new Gazebo 1.9.4 is released and you confirm your plugins are building.

**Comment by piyushk** [comment]
That explains it! gazebo_ros_video displays a ros image topic on an ogre texture inside Gazebo. I've been using it to display information on my robot laptop screen for human-robot experiments. 

It is close to stable, and only a few small features need to be finalized. However, video plugin usage in gazebo over URDF is blocked on this pull request: https://bitbucket.org/osrf/gazebo/pull-request/610/allows-urdf-parser-to-parse-visual-plugins

**Comment by piyushk** [comment]
Also, one of the things I am not sure about this plugin is that I am currently using the global callback queue (AFAIK the image_transport API does not support custom callback queues). See my question here: http://answers.gazebosim.org/question/1963/whats-the-advantage-of-not-using-the-global-ros/

If you have any insight on the question, I can modify the plugin accordingly.

Thanks!

**Comment by davetcoleman** [comment]
I'm afraid I do not have any insight into global callback stuff.

**Comment by piyushk** [comment]
I have a successful build against gazebo-prerelease 1.9.4-2. 

Jenkins log: http://jenkins.willowgarage.com:8080/view/HbinP64/job/ros-hydro-segbot-gazebo-plugins_binarydeb_precise_amd64/16/console

**Comment by piyushk** [comment]
Pull request for gazebo_ros_video plugin: #86
