### ISSUE TITLE
[ros2] Flakey tests

### ISSUE THREAD

**Issue by kev-the-dev** [ros-simulation/gazebo_ros_pkgs#780]
The gazebo plugin tests on the ros2 branch occasionally fail. It seems the callbacks for the ROS timers in these plugins sometimes are never called, therefore the messages are not published. This occurs both when the plugins are launched by the test or if run independently.

**Comment by kev-the-dev** [comment]
I noticed that after closing some other processes on my machine, this occurs much less often. Perhaps the executor is just being starved when the system is under load.

**Comment by chapulina** [comment]
I observed once that something happened that let `gzserver` keep running even after the tests were over. This made all subsequent test runs to fail because a new `gzserver` couldn't be started. I wonder if this is the same case and whether we can make sure the `gzserver` process is killed even if the test is interrupted.

**Comment by dhood** [comment]
fyi @ironmig (in response to a comment that has been edited out now): if you want docker containers to not have cross-talk (for ROS 2) you can start them [like this](https://github.com/ros2/ci/pull/204)

**Comment by dhood** [comment]
edit: I meant to link to the PR not the issue: https://github.com/ros2/ci/pull/204

**Comment by kev-the-dev** [comment]
Thanks!

**Comment by kev-the-dev** [comment]
@chapulina I think gazebo is shutting down okay. Here's one of the logs:

```
8: -- run_test.py: invoking following command in '/home/developer/workspaces/build/gazebo_ros/test':
8:  - /home/developer/workspaces/build/gazebo_ros/test/test_plugins --gtest_output=xml:/home/developer/workspaces/build/gazebo_ros/test_r
esults/gazebo_ros/test_plugins.gtest.xml  
8: [==========] Running 5 tests from 1 test case.
8: [----------] Global test environment set-up.
8: [----------] 5 tests from Plugins/TestPlugins
8: [ RUN      ] Plugins/TestPlugins.TestTopicsReceived/0
8: Gazebo multi-robot simulator, version 9.2.0              
8: Copyright (C) 2012 Open Source Robotics Foundation.
8: Released under the Apache 2 License.                           
8: http://gazebosim.org                                 
8:                                            
8: [WARN] [proper_init]: Publishing                   
8: [WARN] [proper_init]: Publishing    
8: [Msg] Waiting for master.
8: [Msg] Connected to gazebo master @ http://127.0.0.1:11345
8: [Msg] Publicized address: 172.17.0.2               
8: [       OK ] Plugins/TestPlugins.TestTopicsReceived/0 (2635 ms)
8: [ RUN      ] Plugins/TestPlugins.TestTopicsReceived/1
8: Gazebo multi-robot simulator, version 9.2.0
8: Copyright (C) 2012 Open Source Robotics Foundation.
8: Released under the Apache 2 License.
8: http://gazebosim.org
8:
8: [INFO] [gazebo_ros_node]: ROS was initialized without arguments.
8: /home/developer/workspaces/src/gazebo_ros_pkgs/gazebo_ros/test/test_plugins.cpp:126: Failure
8: Expected equality of these values:
8:   topics_received_from
8:     Which is: 0
8:   topics.size()
8:     Which is: 1
8: [WARN] [create_node_without_init]: Publishing
8: [Msg] Waiting for master.
8: [Msg] Connected to gazebo master @ http://127.0.0.1:11345
8: [Msg] Publicized address: 172.17.0.2
8: [  FAILED  ] Plugins/TestPlugins.TestTopicsReceived/1, where GetParam() = 80-byte object <C0-76 BD-A6 1B-56 00-00 20-00 00-00 00-00 00
-00 20-00 00-00 00-00 00-00 65-73 2F-73 72-63 2F-67 90-76 BD-A6 1B-56 00-00 B0-76 BD-A6 1B-56 00-00 B0-76 BD-A6 1B-56 00-00 00-00 00-00 0
0-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00> (16319 ms)
8: [ RUN      ] Plugins/TestPlugins.TestTopicsReceived/2
8: Gazebo multi-robot simulator, version 9.2.0
8: Copyright (C) 2012 Open Source Robotics Foundation.
8: Released under the Apache 2 License.
8: http://gazebosim.org
────────────────────────────
```

You can see for the second test it prints ``` [INFO] [gazebo_ros_node]: ROS was initialized without arguments.``` which comes from the plugin for that test so it seems like it is being loaded in

**Comment by chapulina** [comment]
It looks like the plugin just took too long to start publishing, you can see `[WARN] [create_node_without_init]: Publishing` right after the test fails. Maybe we can change the plugin's timer to start publishing straight away instead of waiting 1 s to publish the first message?

**Comment by kev-the-dev** [comment]
To make things even weirder, this message that it is publishing is triggered whenever gazebo is closed. So the timer is only called once the SIGINT is received

**Comment by kev-the-dev** [comment]
Have not seen this again. This was likely caused through interactions with another gazebo instance I had running in a different container
