### ISSUE TITLE
[ROS2] tf publisher stamp 

### ISSUE THREAD

**Issue by routiful** [ros-simulation/gazebo_ros_pkgs#840]
I have tried to make map using Cartographer but I found that the time is different between two nodes.

I ran a tf2_echo to show that the tf is working well. Left terminal shows tf2_echo between map frame and odom frame. Right terminal shows tf2_echo between odom frame and base_footprint.
You can find that the time has quite different.

![screenshot from 2018-11-19 17-46-49](https://user-images.githubusercontent.com/7092473/48695884-ade0c700-ec23-11e8-9dec-7c610b1015a7.png)

Because Cartographer using chrono or ROS time however the diff_drive in ROS2 package publishes odometry tf with gazebo common time.

https://github.com/ros-simulation/gazebo_ros_pkgs/blob/73a12b7c9bbfebd9a0030bc4f2f394f64228c05e/gazebo_plugins/src/gazebo_ros_diff_drive.cpp#L492

How can I sync this two nodes?

**Comment by chapulina** [comment]
You need to make sure that:

* You launch Gazebo with the `gazebo_ros_init` plugin
* Set `use_sim_time` on your Cartographer nodes

See the migration guide [here](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-ROS-Clocks-and-sim-time).

**Comment by chapulina** [comment]
Let me know if that works for you and then we can close this issue.

**Comment by routiful** [comment]
Great! It works :)
