### ISSUE TITLE
Error while using gazebo_ros_diff_drive plugin 

### ISSUE THREAD

**Issue by trishantroy** [ros-simulation/gazebo_ros_pkgs#841]
Hey,
I am using a Pioneer_2DX bot in my simulation. I want to control the bot. So, I tried using the gazebo_ros_diff_drive. I am getting missing <publishOdomTF> default is ture error while  launch model with plugin.

How to resolve this issue?

Thanks in advance.

trishant@Eurus-Holmes:~/syscon_ws$ roslaunch gazebo_tutorials hello.launch 
... logging to /home/trishant/.ros/log/f5d56ef6-ec4d-11e8-a6f4-2c6e8522ef61/roslaunch-Eurus-Holmes-13958.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Eurus-Holmes:42227/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)

auto-starting new master
process[master]: started with pid [13968]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f5d56ef6-ec4d-11e8-a6f4-2c6e8522ef61
process[rosout-1]: started with pid [13981]
started core service [/rosout]
process[gazebo-2]: started with pid [13987]
process[gazebo_gui-3]: started with pid [14002]
[ INFO] [1542668022.789132024]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1542668022.789766111]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1542668022.849698574]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1542668022.851007024]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1542668023.227224121]: Hello World!
[ INFO] [1542668023.241100122]: DiffDrive missing <robotNamespace>, defaults is pioneer2dx
[ INFO] [1542668023.241195006]: Starting plugin DiffDrive(ns = pioneer2dx/)
[ INFO] [1542668023.241262939]: DiffDrive(ns = pioneer2dx/): <rosDebugLevel> = na
[ INFO] [1542668023.242282809]: DiffDrive(ns = pioneer2dx/): <tf_prefix> = pioneer2dx
[ WARN] [1542668023.242521021]: DiffDrive(ns = pioneer2dx/): missing <publishOdomTF> default is ture
[ INFO] [1542668023.243918919]: DiffDrive(ns = pioneer2dx/): Try to subscribe to cmd_vel
[ INFO] [1542668023.246940416]: DiffDrive(ns = pioneer2dx/): Subscribe to cmd_vel
[ INFO] [1542668023.247718245]: DiffDrive(ns = pioneer2dx/): Advertise odom on odom 
[ INFO] [1542668023.271091518, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1542668023.345188425, 0.083000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1542668023.349224386, 0.086000000]: Physics dynamic reconfigure ready.

**Comment by chapulina** [comment]
Hi @trishantroy, this issue tracker is for bugs and feature requests, and it looks like you're looking for help using the diff drive plugin. I recommend you ask your question at http://answers.gazebosim.org and add information about what you've installed, which world, launch files and software versions you're running.

**Comment by trishantroy** [comment]
Okay, sure.
