### ISSUE TITLE
[ros2] Can't respawn robot using /spawn_entity

### ISSUE THREAD

**Issue by nzlz** [ros-simulation/gazebo_ros_pkgs#865]
Hello everyone,

As part of a Reinforcement Learning task using gazebo I need to be able to reset the pose of a robot, [MARA](https://github.com/AcutronicRobotics/MARA) in this case. The normal behavior of the process won't be to reset the model, but one of the use cases is that the robot gets stuck after selecting an undesired action (Trajectory). Since the robot will lose plenty of time while its stuck, it is convenient that the pose of the robot is reset to the initial one.

My first idea has been to first delete the robot entity, and then spawn it again. But I am struggling with the re-spawning part. Know that **I am completely open to any different approach**, like setting poses manually or anything. 

Quoting myself from [this](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/863#issuecomment-450655312) issue:

> My problems come when I try to spawn the [MARA](https://github.com/AcutronicRobotics/MARA) back again. First, I delete the entity successfully. Then, I try to spawn the robot the same way as in [this file](https://github.com/AcutronicRobotics/MARA/blob/master/mara_utils_scripts/scripts/spawn_entity.py) or even use the LaunchService -> LaunchDescription containing a node that launches the same `spawn_entity` file. But the result is the same, gazebo **process dies or the robot simply is not spawning**.

Just to clarify, I manage to spawn MARA successfully in the initialization. But not after that. I have tried manually pausing the simulation while the re-spawning has to occur, but it has no effect.

I have to mention that (gazebo+ros) are running in a different process. The learning script communicates with them successfully anyway.

```python3
    # Create the LauchService and feed the LaunchDescription obj. to it.
    ls = LaunchService()
    ls.include_launch_description(ld)
    p = Process(target=ls.run)
    p.start()
```

**Note**: Simple models re-spawn successfully ([issue](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/863#issuecomment-450655312)), but they are not initially launched in the separate process. 

### Setup
Ubuntu 18.04, Gazebo 9.6.0, ROS Crystal.

**Comment by chapulina** [comment]
If you run Gazebo in verbose mode, do you see any helpful error messages before it crashes?

Also, could you try getting a backtrace using gdb? Run `gdb gzserver` instead of `gazebo`, and you can run `gzclient` on a separate terminal if you need the GUI.

**Comment by nzlz** [comment]
## Solved
### Port time commands (pause / reset) https://github.com/ros-simulation/gazebo_ros_pkgs/pull/866
Since this is completed/under development, it is a better idea if I just use `reset_world`/`reset_simulation` services. 

**UPDATE2**: I almost managed to make it work using the new reset_simulation service. 
`ros2 service call /reset_simulation std_srvs/Empty
` But the robot loses all joint forces after the simulation is reset.
I'm curious why reset_simulation manages to reset the model but not reset_world..

### Continuing the spawn issue
---
**UPDATE1**: Sorry so many things to do, I forgot to check you hint to `gdb gzserver`! I can't launch gazebo this way:
```
[ERROR] [launch]: process[gdb-1] process has died [pid 12376, exit code 1, cmd 'gdb gzserver --verbose -s libgazebo_ros_factory.so /home/nestor/ros2_mara_ws/install/share/mara_gazebo/worlds/empty_speed_up.world']
```
---

Gazebo is running in another thread so I only get important INFO messages like : 
```
[INFO] [launch]: process[gazebo-1]: started with pid [10391]
```
Or when it chrashes:
```
[ERROR] [launch]: process[gazebo-1] process has died [pid 10732, exit code 255, cmd 'gazebo --verbose -s libgazebo_ros_factory.so /home/nestor/ros2_mara_ws/install/share/mara_gazebo/worlds/empty_speed_up.world'].
```

What I see is that the execution gets stuck at  `rclpy.spin_until_future_complete(node2, future2)`, which is the spawn process. If I comment `#` it the execution continues but no spawn is happening anyway. (Note that this is just test code.)

```python3
    def reset_hard(self):
        # delete - WORKING
        node1 = rclpy.create_node('minimal_client1')
        delete_cli = node1.create_client(DeleteEntity, '/delete_entity')
        while not delete_cli.wait_for_service(timeout_sec=1.0):
            node1.get_logger().info('service not available, waiting again...')

        delete_request = DeleteEntity.Request()
        delete_request.name = "mara"

        future1 = delete_cli.call_async(delete_request)
        rclpy.spin_until_future_complete(node1, future1)
        print("delete completed")

        #spawn - NOT WORKING
        node2 = rclpy.create_node('minimal_client2')
        spawn_cli2 = node2.create_client(SpawnEntity, '/spawn_entity')

        prefix_path = get_prefix_path('mara_description')
        assert os.path.isdir(prefix_path)

        content = ""
        with open(prefix_path + "/share/mara_description/urdf/mara_robot_camera_top.urdf", 'r') as content_file:
            content = content_file.read()

        req = SpawnEntity.Request()
        req.name = "mara"
        req.xml = content
        req.robot_namespace = ""
        req.reference_frame = "world"

        while not spawn_cli2.wait_for_service(timeout_sec=1.0):
            node2.get_logger().info('service not available, waiting again...')
        future2 = spawn_cli2.call_async(req)
        print("start spinning until complete")
        rclpy.spin_until_future_complete(node2, future2)
        print("finished spinning")

        node1.destroy_node()
        node2.destroy_node()
```

**Comment by nzlz** [comment]
I updated the comment above (section _Port time commands (pause / reset)_). I will ask in gazebo answers once https://github.com/ros-simulation/gazebo_ros_pkgs/pull/866 is accepted, as I don't think this is related to the new `reset_simulation` code.


UPDATE http://answers.gazebosim.org/question/21611/ros2-reset_worldreset_simulation-fail-with-urdf/

**Comment by chapulina** [comment]
I responded some of your points on Gazebo Answers. Let me address the other ones which are here but not there:

> I'm curious why reset_simulation manages to reset the model but not reset_world.

I think the name of these 2 functionalities are not descriptive enough and may cause a lot of confusion. Looking at the [implementation](https://bitbucket.org/osrf/gazebo/src/582827025ea59c832cc50e33d64a07ae13cad76a/gazebo/physics/World.cc?fileviewer=file-view-default#World.cc-1273) inside Gazebo, these are the effects of the 2 services:

* `reset_world`: Calls `World::ResetEntities`, which resets the pose, velocities and forces of all models, their links and joints, as well as their plugins.
* `reset_simulation`: Calls `World::Reset`, which besides calling `ResetEntities`, also resets:
    * The random seed
    * Simulation time and real time
    * Calls `Reset` on all world plugins
    * Fires the `worldReset` event

So the reason why one affects your model but not the other comes from how your plugin that sets forces is handling these all these effects.

> gdb gzserver! I can't launch gazebo this way

It looks like you're using `roslaunch`? Try just `gdb gzserver` in a terminal, and inside `gdb`, do `r --verbose -s libgazebo_ros_factory.so /home/nestor/ros2_mara_ws/install/share/mara_gazebo/worlds/empty_speed_up.world`.

**Comment by nzlz** [comment]
First of all thanks for your help, from your explanations and some test I have done I'm almost 100% sure we have a problem with the mara joint plugin. So I will follow this error in gazebo answers (will answer there after this).

Anyway, just in case I managed to get the log. There are 3 scenarios after a failing spawn-process:

1. No error, but no spawn neither.
2. 
```bash
malloc_consolidate(): invalid chunk size
munmap_chunk(): invalid pointer
[ERROR] [launch]: process[gazebo-1] process has died [pid 12629, exit code 255, cmd 'gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/nestor/ros2_mara_ws/install/share/mara_gazebo/worlds/empty_speed_up.world'].
```
3. 
```bash
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::physics::Model; typename boost::detail::sp_member_access<T>::type = gazebo::physics::Model*]: Assertion `px != 0' failed.
[ERROR] [launch]: process[gazebo-1] process has died [pid 13145, exit code 255, cmd 'gazebo --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/nestor/ros2_mara_ws/install/share/mara_gazebo/worlds/empty_speed_up.world'].
```

I don't think these errors point to anywhere or help at all, so everything must be related to a bad failing plugin on our side. 

This issue can be closed on my side, please feel free to close!
