### ISSUE TITLE
[gazebo_ros_pkgs] crash when selecting spawned URDF model

### ISSUE THREAD

**Issue by christian-rauch** [ros-simulation/gazebo_ros_pkgs#870]
Gazebo 9 (on ROS melodic) crashes after a spawned URDF model is selected in the GUI.

Steps to reproduce:

1. install `ros-melodic-franka-description` (this happens with other URDF files too)
2. start Gazebo with an empty world: `roslaunch gazebo_ros empty_world.launch`
3. create URDF: `xacro /opt/ros/melodic/share/franka_description/robots/panda_arm_hand.urdf.xacro > panda.urdf`
4. spawn model: `rosrun gazebo_ros spawn_model -file panda.urdf -urdf -model panda`
5. in GUI select `World > Models > panda`

After this, Gazebo crashes with:

> gzclient: /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.

This used to work with ROS kinetic / Gazebo 7

**Comment by chapulina** [comment]
What Gazebo version are you using? I think this has been fixed in the latest Gazebo 9 release by [this PR](https://bitbucket.org/osrf/gazebo/pull-requests/3033/fix-model-bounding-box/diff).

**Comment by christian-rauch** [comment]
The latest released version of `ros-melodic-gazebo-ros` (2.8.4) and `gazebo9` (9.0.0).

**Comment by chapulina** [comment]
You'll need to install Gazebo 9 from OSRF's packages as instructed [here](http://gazebosim.org/tutorials?tut=install_ubuntu&cat=install#Alternativeinstallation:step-by-step). The latest version is 9.6.0.

**Comment by christian-rauch** [comment]
Oh, I thought these are only for non-ROS usage.
Why are the packages in the ROS repo not updated? Are the packages from this repo compatible with ROS?

**Comment by chapulina** [comment]
ROS uses the Gazebo [version on Ubuntu](https://packages.ubuntu.com/source/bionic/gazebo) by default, but as long as it is major version 9 it should work with Melodic and Crystal.

**Comment by christian-rauch** [comment]
Ups, I thought it's using the `gazebo9` package from the ROS repo: http://packages.ros.org/ros/ubuntu/pool/main/g/gazebo9/ but I just saw now that it's not released for `bionic` (just `artful`).
Thanks for pointing me to the gazebo repo. I am going to test with the newest release.

**Comment by christian-rauch** [comment]
Problem solved with updated Gazebo packages from osrf repo. Thanks.
