### ISSUE TITLE
climbing stairs ROS gazebo

### ISSUE THREAD

**Issue by timdori** [ros-simulation/gazebo_ros_pkgs#896]
Hey guys,

right now im working in building a robot which can climb stairs. Right now i have no idea how i could simulate the wheel moving up at the wall.
Is there already any robot package doing this?
My last idea was to check if there is a collision of the front wheels with a static object and if so it should move upwards. Is this the right way? If yes how can i check the collision?

Thank you :)

**Comment by chapulina** [comment]
Hi @timdori , this kind of question is better suited for http://answers.gazebosim.org ; this issue tracker is for bug reports and feature requests.

Closing this, see you at Gazebo Answers!
