### ISSUE TITLE
[gazebo_plugins] Add Ackermann Drive Plugin for car-like robots

### ISSUE THREAD

**Issue by naiveHobo** [ros-simulation/gazebo_ros_pkgs#900]
A generalized Ackermann Drive plugin as a standard plugin would be a great addition.

I can get this going on a fork. Any ideas or suggestions are welcome.

**Comment by DexterFromLab** [comment]
I'am join to request

**Comment by SteveMacenski** [comment]
Googling around for "gazebo plugin ackermann" I see a number of options available. None of them are perfect, but I think everyone would be open to you cleaning up a C++ version of one for this repo!

**Comment by chapulina** [comment]
An Ackermann drive plugin was added on #947 for ROS 2.

**Comment by SteveMacenski** [comment]
@chapulina good enough for me. I think that makes this valid to close.

**Comment by naiveHobo** [comment]
Yes, looks good!
