### ISSUE TITLE
calling gazebo error

### ISSUE THREAD

**Issue by Lewis-Lu** [ros-simulation/gazebo_ros_pkgs#904]
it seems like wrong configuration of ignition
```
[Err] [ClientConfig.cc:222] Error copying default configuration file from [/usr/share/ignition/fuel_tools//config.yaml] to [/home/lewis/.ignition/fuel/config.yaml]

[Err] [Err] [ClientConfig.cc:222] Error copying default configuration file from [/usr/share/ignition/fuel_tools//config.yaml] to [/home/lewis/.ignition/fuel/config.yaml]

[ClientConfig.cc:222] Error copying default configuration file from [/usr/share/ignition/fuel_tools//config.yaml] to [/home/lewis/.ignition/fuel/config.yaml]
```
I can open gazebo with empty world, but with this error, importing existing .world file 
So how to configure ignition. I just follow this link step by step:
[http://gazebosim.org/tutorials?tut=install_ubuntu&cat=install](url)

**Comment by Sarath18** [comment]
Can you recompile Fuel-tools and try again?
According to @caguero, this issue has been fixed in Ignition Fuel tools.

Reference: https://bitbucket.org/osrf/gazebo/pull-requests/2800/download-a-model-from-ignition-fuel/diff
