### ISSUE TITLE
Odometry is not  updating 

### ISSUE THREAD

**Issue by Mbadra96** [ros-simulation/gazebo_ros_pkgs#913]
The odometry topic doesn't update the robot pose while moving it or changing its position using gazebo tools.
I have tried it using turtlebot and Husky robots
and I'm just running this command to run turtlebot in gazebo 
`roslaunch turtlebot_gazebo turtlebot_world.launch`
then in another terminal `rostopic echo /odom ` 
the message is published but the position in it doesn't change

**Comment by chapulina** [comment]
@Mbadra96 , this sounds like it may not be a bug in `gazebo_ros_pkgs`. Feel free to ask a question at http://answers.gazebosim.org with more details of how you've setup your workspace and what you've tried to debug the issue.

I'll close this issue for now, but if you find out it's a bug with `gazebo_ros_pkgs` feel free to reopen with more info.
