### ISSUE TITLE
document video plugin on wiki

### ISSUE THREAD

**Issue by davetcoleman** [ros-simulation/gazebo_ros_pkgs#92]
https://github.com/ros-simulation/gazebo_ros_pkgs/pull/86

**Comment by piyushk** [comment]
Done :)

**Comment by piyushk** [comment]
For reference: http://gazebosim.org/wiki/Tutorials/1.9/ROS_Motor_and_Sensor_Plugins#Video_Plugin

**Comment by davetcoleman** [comment]
thanks!
