### ISSUE TITLE
gazebo_plugins: gazebo_ros_openni_kinect plugin crashing

### ISSUE THREAD

**Issue by bit-pirate** [ros-simulation/gazebo_ros_pkgs#94]
```
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  rospack could not find the image_transport package containing image_transport::PublisherPlugin
/opt/ros/hydro/lib/gazebo_ros/gzserver: line 17:  7965 Aborted                 (core dumped) gzserver $final
```

You can reproduce this by launching the turtlebot simulator:

```
roslaunch turtlebot_gazebo turtlebot_empty_world.launch
```

http://www.ros.org/wiki/turtlebot_simulator

**Comment by davetcoleman** [comment]
Sounds like a ROS issue, not a gazebo plugin issue. What version of ROS do you have and do you have multiple versions installed? Try removing older versions of ROS. This [issue](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/83) also had rospack problems.

**Comment by bit-pirate** [comment]
The might be true. I have (to have) Fuerte installed and that might mix up things.

But I actually believe this is just a temporal glitch, since when compiling my (and the ros gazebo) plugins from source, everything runs smoothly.

I will close this issue now and reopen it in case this problem comes back.
