### ISSUE TITLE
[ros2] Spawn-Entity Node Missing?

### ISSUE THREAD

**Issue by TomShkurti** [ros-simulation/gazebo_ros_pkgs#964]
[This wiki page](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Spawn-and-delete) claims there is a convenience node called spawn-entity in gazebo-ros which works like the old spawn-model node, but when attempting to run the example command (or otherwise actually run spawn-model) no such executable is found. Calling the underlying service does still work, but that convenience node was much more, well, convenient.

**Comment by chapulina** [comment]
The port is still on a pull request, #948. You're welcome to give that a try.

**Comment by TomShkurti** [comment]
Yes, that works as it should. We'll just be building gazebo_ros from that fork specifically until such time as it is merged.

**Comment by chapulina** [comment]
Thanks for trying it out. I'll close this issue once that's merged.

**Comment by chapulina** [comment]
#948 has been merged and will be released in the next Dashing sync.
