### ISSUE TITLE
gazebo_ros_openni_kinect from 2 different gazebo models colliding?

### ISSUE THREAD

**Issue by piyushk** [ros-simulation/gazebo_ros_pkgs#99]
Downstream bug report: https://github.com/utexas-bwi/segbot_simulator/issues/11

This is a low priority bug for me. If one of you guys can spot any obvious problems, then let me know. Otherwise I will follow up on this once the new version of gazebo/sdformat/gazebo-ros-pkgs and segbot-simulator have been released (making it easier to reproduce the error).

Both robots Initialize at [Screenshot 1](http://farnsworth.csres.utexas.edu/share/Screenshot1.png). 
- Both robots are running a very simple collision model and have 1 collision element each.
- They use gazebo_ros_openni_kinect as a simulated kinect sensor
- They move inside gazebo using gazebo_ros_planar_move. 

Note the bubble in the depth image for robot 1 in the bottom left hand corner. As robot 2 moves away, the depth image changes and eventually the bubble goes away. 
[Screenshot 2](http://farnsworth.csres.utexas.edu/share/Screenshot2.png) 
[Screenshot 3](http://farnsworth.csres.utexas.edu/share/Screenshot3.png) 
[Screenshot 4](http://farnsworth.csres.utexas.edu/share/Screenshot4.png)

This problem does not exist with a single robot. It seems like multiple depth cameras are somehow interfering with one another.

Thanks!
Piyush

**Comment by j-rivero** [comment]
Seems fixed. Reopen please if needed.
